<script setup lang="ts">
import { useQuery } from '../lib/query'
import { stamp, statusName } from '../lib/format'
import PageState from './PageState.vue'
interface Source { id:string; configured:boolean; installed:boolean; status:string; deadline_seconds?:number; capabilities:Record<string,string>; notes:string[] }
interface Coverage { source:string; rows:number; instruments?:number; last_date?:string; last_source_time?:string; last_fetch_time?:string }
interface Sources { effective_provider:string; configured_provider:string; credential_origin:string; legacy_secret_storage:boolean; history_repair_required:boolean; legacy_history_rows:number; data_contract_version:string; minute_sync_enabled:boolean; sources:Source[]; coverage:{daily:Coverage[];quotes:Coverage[]}; notes:string[] }
const q=useQuery<Sources>('/api/workspace/data-sources')
const names:Record<string,string>={credentials_missing:'未配置 Token',permission_not_verified:'已配置，权限待验证',public_source_not_verified:'公开源，实时资格未验证',package_missing:'未安装数据依赖',disabled:'未启用',unqualified:'未取得资格',qualified_config_only:'仅配置资格通过',sources_missing:'未配置 RSS',source_not_verified:'来源待验证',demo_only:'仅演示'}
</script>
<template><div class="card section" data-testid="data-connections"><div class="card-header"><div><h2>后端数据接入</h2><p>配置、入库覆盖与实时资格分开；刷新本卡片不会调用外部接口。</p></div><button class="button small" @click="q.reload">读取接入状态</button></div><PageState :loading="q.loading.value" :error="q.error.value" @retry="q.reload"><div v-if="q.data.value" class="card-body"><div class="notice">有效链路 {{q.data.value.effective_provider}} · 配置 {{q.data.value.configured_provider}} · {{q.data.value.data_contract_version}} · 分钟同步 {{q.data.value.minute_sync_enabled ? '已打开（仍需权限）' : '关闭'}}</div><div v-if="q.data.value.legacy_secret_storage" class="notice warning-notice">检测到旧版数据库行情凭据；仅显示存在性，不回显内容。建议按部署文档迁移到服务端私有环境文件。</div><div v-if="q.data.value.history_repair_required" class="notice warning-notice">{{q.data.value.legacy_history_rows}} 根旧口径日线需要完整重抓。修复完成前阻断新的指标/决策生成，不对原值直接乘系数猜测。</div><div class="table-scroll"><table><thead><tr><th>数据源</th><th>配置 / 依赖</th><th>当前含义</th><th>能力与边界</th></tr></thead><tbody><tr v-for="source in q.data.value.sources" :key="source.id"><td><strong>{{source.id}}</strong></td><td>{{source.configured ? '已配置' : '未配置'}} / {{source.installed ? '已具备' : '未安装'}}<small v-if="source.deadline_seconds">每次调用截止 {{source.deadline_seconds}} 秒</small></td><td>{{names[source.status] ?? statusName(source.status)}}</td><td><details><summary>查看已接入能力</summary><p v-for="(value,key) in source.capabilities" :key="key">{{key}}：{{value}}</p><p v-for="note in source.notes" :key="note">{{note}}</p></details></td></tr></tbody></table></div><details class="details-block"><summary>已入库覆盖（不等于当前网络可用）</summary><p v-if="!q.data.value.coverage.daily.length">尚无持久日线。下方先点击“更新跟踪池行情”。</p><p v-for="row in q.data.value.coverage.daily" :key="row.source">{{row.source}} · {{row.rows}} 根 · {{row.instruments}} 只 · 最后日期 {{row.last_date}}</p><p v-for="row in q.data.value.coverage.quotes" :key="row.source">{{row.source}} · 最后已验证源时间 {{stamp(row.last_source_time)}} · 抓取时间 {{stamp(row.last_fetch_time)}}</p></details><p class="small-note">真实数据请用持久化配置启动，不要继续使用会退出即删除数据的 Mock demo。Token 只能由本人配置到服务端，网站不索要旧项目登录文件。</p></div></PageState></div></template>
