<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { Sparkles, Download, Upload, Check, X, RefreshCw, FileText } from 'lucide-vue-next'
import { api, download, errorText } from '../lib/api'
import { useQuery } from '../lib/query'
import { stamp, statusName } from '../lib/format'
import type { ResearchJob, ResearchResult } from '../lib/types'
import PageState from './PageState.vue'
import Badge from './Badge.vue'
const props = defineProps<{ code?: string; kind?: 'etf' | 'daily'; archive?: boolean }>()
const draftCode = ref(props.code ?? ''), includeHoldings = ref(false), busy = ref(false), error = ref(''), message = ref(''), selected = ref(''), note = ref('')
const kind = computed(() => props.kind ?? 'etf')
const list = useQuery<{ items: ResearchJob[] }>(() => `/api/workspace/research-jobs?limit=50${props.archive ? '' : '&kind=' + kind.value}${props.code ? '&code=' + encodeURIComponent(props.code) : ''}`)
const detail = useQuery<ResearchJob>(() => selected.value ? `/api/workspace/research-jobs/${selected.value}` : null)
const result = computed(() => detail.data.value?.result)
watch(() => props.code, value => { draftCode.value = value ?? ''; selected.value = ''; includeHoldings.value = false })
async function act(work: () => Promise<void>) { if (busy.value) return; error.value = ''; message.value = ''; busy.value = true; try { await work() } catch (e) { error.value = errorText(e) } finally { busy.value = false } }
async function create() { await act(async () => { const data = await api<{ job: ResearchJob }>('/api/workspace/research-jobs', { method: 'POST', body: { kind: kind.value, ...(kind.value === 'etf' ? { ts_code: draftCode.value.trim().toUpperCase() } : {}), include_holdings: includeHoldings.value, request_key: crypto.randomUUID() } }); selected.value = data.job.job_id; await list.reload(); message.value = '研究任务已建立，证据已固定。网页没有调用模型；请导出研究包或连接已配对的设备。' }) }
async function upload(event: Event) { const el = event.target as HTMLInputElement, file = el.files?.[0]; if (!file || !selected.value) return; el.value = ''; await act(async () => { if (file.size > 150000) { message.value = '结果文件不能超过 150 KB。'; return } let data: unknown; try { data = JSON.parse(await file.text()) } catch { message.value = '请选择有效的 result.json，Markdown 报告不能直接作为结构化结果导入。'; return } await api(`/api/workspace/research-jobs/${selected.value}/result`, { method: 'POST', body: data }); await detail.reload(); await list.reload(); message.value = '结构化结果已通过接口校验，仍为待审核候选，未改变任何技术指标或研究动作。' }) }
async function review(decision: 'accepted' | 'rejected') { const job = detail.data.value; if (!job?.result_hash) return; if (decision === 'accepted' && !window.confirm('确认已检查证据、数据日期和局限，并将这份候选标记为已审核？这不会升级预测或策略资格。')) return; await act(async () => { await api(`/api/workspace/research-jobs/${job.job_id}/review/${decision}`, { method: 'POST', body: { result_hash: job.result_hash, note: note.value } }); await detail.reload(); await list.reload() }) }
async function transition(action: 'cancel' | 'retry') { if (!selected.value) return; await act(async () => { await api(`/api/workspace/research-jobs/${selected.value}/${action}`, { method: 'POST' }); await detail.reload(); await list.reload() }) }
async function exportBundle() { if (!selected.value) return; await act(() => download(`/api/workspace/research-jobs/${selected.value}/export`, `evidence-${selected.value}.json`)) }
let timer: ReturnType<typeof setInterval> | undefined
onMounted(() => { timer = setInterval(() => { if (!document.hidden && !busy.value && (list.data.value?.items.some(j => ['queued', 'running'].includes(j.status)) || ['queued', 'running'].includes(detail.data.value?.status ?? ''))) { void list.reload(); if (selected.value) void detail.reload() } }, 15000) })
onBeforeUnmount(() => clearInterval(timer))
</script>
<template>
<div class="notice"><Sparkles :size="16"/><span>AI 解释与技术决策分开。未配置 AI 时，图表、自选和持仓照常使用；外部结果必须经过校验与人工审核。</span></div>
<div v-if="error" class="form-error" role="alert">{{ error }}</div><div v-if="message" class="notice" role="status">{{ message }}</div>
<div v-if="!archive" class="card section"><div class="card-header"><h2>{{ kind === 'daily' ? '创建每日复盘草稿' : '创建 ETF 分析草稿' }}</h2><RouterLink to="/settings" class="text-button">连接本地 AI</RouterLink></div><div class="card-body"><form @submit.prevent="create"><div class="form-grid"><label v-if="kind === 'etf'" class="field">场内 ETF / LOF 代码<input v-model="draftCode" aria-label="AI 研究基金代码" placeholder="512480.SH" required pattern="[0-9]{6}\.(SH|SZ|BJ)" :readonly="!!code" maxlength="9"></label><label class="field">研究模式<select aria-label="研究模式" disabled><option>固定快照解释 · 不允许自由取数或下单</option></select></label><div class="field"><span>输入与执行</span><small>网站固定证据；隔离设备按预算执行。没有设备时可手动导出和导入。</small></div></div><label class="checkbox-label"><input v-model="includeHoldings" type="checkbox">我明确同意把本次相关持仓的成本、份额与风险上下文包含在导出的研究包中。默认不包含。</label><div class="actions" style="margin-top:16px"><button class="button primary" :disabled="busy || (kind === 'etf' && !draftCode)"><Sparkles :size="15"/>建立证据包与任务</button><small>点击才创建；打开此页不会调用模型。</small></div></form></div></div>
<div class="split-grid section"><div class="card"><div class="card-header"><h2><FileText :size="16"/>研究任务</h2><button class="icon-button" aria-label="刷新研究任务" @click="list.reload"><RefreshCw :size="15"/></button></div><PageState :loading="list.loading.value" :error="list.error.value" :empty="!list.data.value?.items.length" title="还没有研究任务" description="在上方建立任务，或从 ETF 详情的 AI 页签开始。" @retry="list.reload"><ul class="job-list"><li v-for="job in list.data.value?.items" :key="job.job_id" :class="{ selected: selected === job.job_id }"><div><button class="job-button" @click="selected = job.job_id">{{ job.kind === 'daily' ? '每日市场复盘' : job.ts_code }} <small>{{ job.job_id.slice(0, 6) }}</small></button><p>{{ job.summary ?? (job.failure_reason ? statusName(job.failure_reason) : '等待研究结果，不会自动发布') }}</p><div class="job-meta"><span>{{ stamp(job.created_at) }}</span><Badge :value="job.status"/><Badge :value="job.review_status"/></div></div></li></ul></PageState></div>
<div class="card"><div class="card-header"><h2>证据与报告</h2><small>与输入哈希绑定</small></div><PageState :loading="detail.loading.value" :error="detail.error.value" :empty="!selected" title="选择一个研究任务" description="查看证据时间、执行情况、模型和审核记录。" @retry="detail.reload"><template v-if="detail.data.value"><div class="card-body"><div class="actions"><Badge :value="detail.data.value.status"/><Badge :value="detail.data.value.quality"/><Badge :value="detail.data.value.review_status"/><Badge v-if="detail.data.value.expired" value="expired" label="已超过任务有效期"/></div><dl class="details-list"><dt>证据截止</dt><dd>{{ stamp(detail.data.value.source_as_of) }}</dd><dt>建立时间</dt><dd>{{ stamp(detail.data.value.created_at) }}</dd><dt>输入哈希</dt><dd class="mono">{{ detail.data.value.input_hash }}</dd><dt>失败原因</dt><dd>{{ detail.data.value.failure_reason ?? '无' }}</dd></dl><div class="actions"><button class="button small" :disabled="busy" @click="exportBundle"><Download :size="14"/>导出证据包</button><button v-if="['queued','running'].includes(detail.data.value.status)" class="button small" :disabled="busy" @click="transition('cancel')">取消任务</button><button v-if="['failed','cancelled'].includes(detail.data.value.status) && !detail.data.value.expired" class="button small" :disabled="busy" @click="transition('retry')">重试同一证据</button></div><label v-if="detail.data.value.status === 'queued' && !detail.data.value.expired" class="field" style="margin-top:20px"><span><Upload :size="13"/> 导入结构化研究结果（result.json）</span><input type="file" accept=".json,application/json" :disabled="busy" @change="upload"><small>必须匹配当前 job_id 和 input_hash，且所有引用均存在于证据包。</small></label>
<template v-if="result"><div class="report-section"><h3>{{ result.producer }} · {{ result.model }}</h3><p>{{ result.summary }}</p><p class="small-note">版本 {{ result.producer_version }} · 研究解释，不是交易建议或概率校准。</p></div><div v-if="result.facts.length" class="report-section"><h3>事实与引用</h3><div v-for="(claim, i) in result.facts" :key="i" class="claim">{{ claim.text }}<small>{{ claim.evidence_ids.join(' · ') }}</small></div></div><div v-if="result.inferences.length" class="report-section"><h3>推断（与事实区分）</h3><div v-for="(claim, i) in result.inferences" :key="i" class="claim">{{ claim.text }}<small>{{ claim.evidence_ids.join(' · ') }}</small></div></div><div class="report-section"><h3>风险 / 冲突 / 数据缺口</h3><ul class="compact-list"><li v-for="(text, i) in [...result.risks, ...result.conflicts, ...result.limitations]" :key="i">{{ text }}</li></ul></div><details v-if="result.report_markdown" class="details-block"><summary>完整报告（安全纯文本展示）</summary><pre class="report-text" data-testid="research-report-text">{{ result.report_markdown }}</pre></details><div v-if="detail.data.value.review_status === 'pending'" class="report-section"><label class="field">人工审核备注<textarea v-model="note" rows="2" maxlength="1000" placeholder="已检查哪些证据、有哪些保留意见"/></label><div class="actions"><button class="button primary" :disabled="busy" @click="review('accepted')"><Check :size="15"/>确认审核</button><button class="button" :disabled="busy" @click="review('rejected')"><X :size="15"/>驳回</button></div></div></template><details class="details-block"><summary>查看固定证据（{{ detail.data.value.evidence?.length ?? 0 }} 项）</summary><pre class="report-text">{{ JSON.stringify(detail.data.value.evidence ?? [], null, 2) }}</pre></details></div></template></PageState></div></div>
</template>
