"""initial schema

Revision ID: 158ca7025305
Revises: 
Create Date: 2026-08-27 01:37:33.733076
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '158ca7025305'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_log_created', 'event_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_event_log_event_type'), 'event_log', ['event_type'], unique=False)
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts_code', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('exchange', sa.String(length=16), nullable=True),
    sa.Column('theme_l1', sa.String(length=64), nullable=True),
    sa.Column('theme_l2', sa.String(length=128), nullable=True),
    sa.Column('benchmark', sa.String(length=32), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instruments_enabled'), 'instruments', ['enabled'], unique=False)
    op.create_index(op.f('ix_instruments_symbol'), 'instruments', ['symbol'], unique=False)
    op.create_index(op.f('ix_instruments_theme_l1'), 'instruments', ['theme_l1'], unique=False)
    op.create_index(op.f('ix_instruments_theme_l2'), 'instruments', ['theme_l2'], unique=False)
    op.create_index(op.f('ix_instruments_ts_code'), 'instruments', ['ts_code'], unique=True)
    op.create_table('news_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('facts_json', sa.JSON(), nullable=False),
    sa.Column('inferences_json', sa.JSON(), nullable=False),
    sa.Column('risk_flags_json', sa.JSON(), nullable=False),
    sa.Column('affected_themes_json', sa.JSON(), nullable=False),
    sa.Column('impact_direction', sa.String(length=16), nullable=True),
    sa.Column('impact_horizon', sa.String(length=16), nullable=True),
    sa.Column('impact_score', sa.Float(), nullable=False),
    sa.Column('llm_model', sa.String(length=128), nullable=True),
    sa.Column('schema_version', sa.String(length=32), nullable=False),
    sa.Column('quality_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_news_source_id')
    )
    op.create_index(op.f('ix_news_items_published_at'), 'news_items', ['published_at'], unique=False)
    op.create_index(op.f('ix_news_items_quality_hash'), 'news_items', ['quality_hash'], unique=False)
    op.create_index(op.f('ix_news_items_source'), 'news_items', ['source'], unique=False)
    op.create_index('ix_news_published', 'news_items', ['published_at'], unique=False)
    op.create_table('provider_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('operation', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('source_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quality_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_provider_audit_time', 'provider_audits', ['created_at'], unique=False)
    op.create_index(op.f('ix_provider_audits_operation'), 'provider_audits', ['operation'], unique=False)
    op.create_index(op.f('ix_provider_audits_provider'), 'provider_audits', ['provider'], unique=False)
    op.create_index(op.f('ix_provider_audits_run_id'), 'provider_audits', ['run_id'], unique=False)
    op.create_table('report_artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=32), nullable=False),
    sa.Column('as_of_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_artifacts_as_of_time'), 'report_artifacts', ['as_of_time'], unique=False)
    op.create_index(op.f('ix_report_artifacts_content_hash'), 'report_artifacts', ['content_hash'], unique=False)
    op.create_index(op.f('ix_report_artifacts_report_type'), 'report_artifacts', ['report_type'], unique=False)
    op.create_table('runtime_settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('task_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('task_name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_task_run_name_started', 'task_runs', ['task_name', 'started_at'], unique=False)
    op.create_index(op.f('ix_task_runs_run_id'), 'task_runs', ['run_id'], unique=True)
    op.create_index(op.f('ix_task_runs_status'), 'task_runs', ['status'], unique=False)
    op.create_index(op.f('ix_task_runs_task_name'), 'task_runs', ['task_name'], unique=False)
    op.create_table('daily_bars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('pre_close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('pct_change', sa.Float(), nullable=True),
    sa.Column('adjust', sa.String(length=8), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('quality_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'trade_date', 'adjust', name='uq_daily_bar_instrument_date_adjust')
    )
    op.create_index('ix_daily_bars_instrument_date', 'daily_bars', ['instrument_id', 'trade_date'], unique=False)
    op.create_index(op.f('ix_daily_bars_quality_hash'), 'daily_bars', ['quality_hash'], unique=False)
    op.create_table('forecast_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('horizon', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('p_up', sa.Float(), nullable=True),
    sa.Column('expected_return', sa.Float(), nullable=True),
    sa.Column('q10', sa.Float(), nullable=True),
    sa.Column('q50', sa.Float(), nullable=True),
    sa.Column('q90', sa.Float(), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('calibration_status', sa.String(length=32), nullable=False),
    sa.Column('similarity_distance', sa.Float(), nullable=True),
    sa.Column('diagnostics_json', sa.JSON(), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'as_of_date', 'horizon', 'model_version', name='uq_forecast_key')
    )
    op.create_index(op.f('ix_forecast_snapshots_as_of_date'), 'forecast_snapshots', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_forecast_snapshots_input_hash'), 'forecast_snapshots', ['input_hash'], unique=False)
    op.create_index(op.f('ix_forecast_snapshots_instrument_id'), 'forecast_snapshots', ['instrument_id'], unique=False)
    op.create_table('holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('target_weight', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id')
    )
    op.create_table('indicator_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('values_json', sa.JSON(), nullable=False),
    sa.Column('technical_score', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('trend_label', sa.String(length=64), nullable=False),
    sa.Column('data_quality', sa.Float(), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'as_of_date', 'version', name='uq_indicator_instrument_date_version')
    )
    op.create_index(op.f('ix_indicator_snapshots_as_of_date'), 'indicator_snapshots', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_indicator_snapshots_input_hash'), 'indicator_snapshots', ['input_hash'], unique=False)
    op.create_index(op.f('ix_indicator_snapshots_instrument_id'), 'indicator_snapshots', ['instrument_id'], unique=False)
    op.create_table('quote_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('quote_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('pre_close', sa.Float(), nullable=True),
    sa.Column('pct_change', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('premium_rate', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('is_realtime', sa.Boolean(), nullable=False),
    sa.Column('degraded_reason', sa.Text(), nullable=True),
    sa.Column('quality_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quote_instrument_time', 'quote_snapshots', ['instrument_id', 'quote_time'], unique=False)
    op.create_index(op.f('ix_quote_snapshots_instrument_id'), 'quote_snapshots', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_quote_snapshots_quality_hash'), 'quote_snapshots', ['quality_hash'], unique=False)
    op.create_index(op.f('ix_quote_snapshots_quote_time'), 'quote_snapshots', ['quote_time'], unique=False)
    op.create_table('signal_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('as_of_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('strategy_version', sa.String(length=32), nullable=False),
    sa.Column('indicator_version', sa.String(length=32), nullable=False),
    sa.Column('forecast_version', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('target_weight', sa.Float(), nullable=True),
    sa.Column('first_step_target_weight', sa.Float(), nullable=True),
    sa.Column('reasons_json', sa.JSON(), nullable=False),
    sa.Column('risks_json', sa.JSON(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_actionable', sa.Boolean(), nullable=False),
    sa.Column('data_quality', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'as_of_time', 'strategy_version', name='uq_signal_key')
    )
    op.create_index('ix_signal_instrument_time', 'signal_snapshots', ['instrument_id', 'as_of_time'], unique=False)
    op.create_index(op.f('ix_signal_snapshots_as_of_time'), 'signal_snapshots', ['as_of_time'], unique=False)
    op.create_index(op.f('ix_signal_snapshots_input_hash'), 'signal_snapshots', ['input_hash'], unique=False)
    op.create_index(op.f('ix_signal_snapshots_instrument_id'), 'signal_snapshots', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_signal_snapshots_state'), 'signal_snapshots', ['state'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signal_snapshots_state'), table_name='signal_snapshots')
    op.drop_index(op.f('ix_signal_snapshots_instrument_id'), table_name='signal_snapshots')
    op.drop_index(op.f('ix_signal_snapshots_input_hash'), table_name='signal_snapshots')
    op.drop_index(op.f('ix_signal_snapshots_as_of_time'), table_name='signal_snapshots')
    op.drop_index('ix_signal_instrument_time', table_name='signal_snapshots')
    op.drop_table('signal_snapshots')
    op.drop_index(op.f('ix_quote_snapshots_quote_time'), table_name='quote_snapshots')
    op.drop_index(op.f('ix_quote_snapshots_quality_hash'), table_name='quote_snapshots')
    op.drop_index(op.f('ix_quote_snapshots_instrument_id'), table_name='quote_snapshots')
    op.drop_index('ix_quote_instrument_time', table_name='quote_snapshots')
    op.drop_table('quote_snapshots')
    op.drop_index(op.f('ix_indicator_snapshots_instrument_id'), table_name='indicator_snapshots')
    op.drop_index(op.f('ix_indicator_snapshots_input_hash'), table_name='indicator_snapshots')
    op.drop_index(op.f('ix_indicator_snapshots_as_of_date'), table_name='indicator_snapshots')
    op.drop_table('indicator_snapshots')
    op.drop_table('holdings')
    op.drop_index(op.f('ix_forecast_snapshots_instrument_id'), table_name='forecast_snapshots')
    op.drop_index(op.f('ix_forecast_snapshots_input_hash'), table_name='forecast_snapshots')
    op.drop_index(op.f('ix_forecast_snapshots_as_of_date'), table_name='forecast_snapshots')
    op.drop_table('forecast_snapshots')
    op.drop_index(op.f('ix_daily_bars_quality_hash'), table_name='daily_bars')
    op.drop_index('ix_daily_bars_instrument_date', table_name='daily_bars')
    op.drop_table('daily_bars')
    op.drop_index(op.f('ix_task_runs_task_name'), table_name='task_runs')
    op.drop_index(op.f('ix_task_runs_status'), table_name='task_runs')
    op.drop_index(op.f('ix_task_runs_run_id'), table_name='task_runs')
    op.drop_index('ix_task_run_name_started', table_name='task_runs')
    op.drop_table('task_runs')
    op.drop_table('runtime_settings')
    op.drop_index(op.f('ix_report_artifacts_report_type'), table_name='report_artifacts')
    op.drop_index(op.f('ix_report_artifacts_content_hash'), table_name='report_artifacts')
    op.drop_index(op.f('ix_report_artifacts_as_of_time'), table_name='report_artifacts')
    op.drop_table('report_artifacts')
    op.drop_index(op.f('ix_provider_audits_run_id'), table_name='provider_audits')
    op.drop_index(op.f('ix_provider_audits_provider'), table_name='provider_audits')
    op.drop_index(op.f('ix_provider_audits_operation'), table_name='provider_audits')
    op.drop_index('ix_provider_audit_time', table_name='provider_audits')
    op.drop_table('provider_audits')
    op.drop_index('ix_news_published', table_name='news_items')
    op.drop_index(op.f('ix_news_items_source'), table_name='news_items')
    op.drop_index(op.f('ix_news_items_quality_hash'), table_name='news_items')
    op.drop_index(op.f('ix_news_items_published_at'), table_name='news_items')
    op.drop_table('news_items')
    op.drop_index(op.f('ix_instruments_ts_code'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_theme_l2'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_theme_l1'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_symbol'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_enabled'), table_name='instruments')
    op.drop_table('instruments')
    op.drop_index(op.f('ix_event_log_event_type'), table_name='event_log')
    op.drop_index('ix_event_log_created', table_name='event_log')
    op.drop_table('event_log')
    # ### end Alembic commands ###
