import {test,expect} from '@playwright/test'

test('personal center persists profile, reauthenticates passwords and closes access without claiming erasure',async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 await page.goto('/register')
 await page.getByLabel('账户',{exact:true}).fill('self-service-browser')
 await page.getByLabel('密码',{exact:true}).fill('fixture-only-browser-password')
 await page.getByLabel('确认密码',{exact:true}).fill('fixture-only-browser-password')
 await page.getByLabel('邀请码',{exact:true}).fill('browser-test-invite')
 await page.getByRole('button',{name:'创建账户并进入总览'}).click()
 await expect(page.locator('.account-text')).toContainText('self-service-browser')
 await page.goto('/profile');await page.getByLabel('显示名称',{exact:true}).fill('隔离测试研究员')
 await page.getByRole('button',{name:'保存修改',exact:true}).click()
 await expect(page.getByRole('status').filter({hasText:'个人资料已保存'})).toBeVisible()
 await page.reload();await expect(page.locator('.profile-identity')).toContainText('隔离测试研究员')
 for(const width of [320,390,768,1440]){
  await page.setViewportSize({width,height:1000})
  await expect.poll(()=>page.evaluate(()=>Math.max(document.body.scrollWidth,document.documentElement.scrollWidth)-innerWidth)).toBeLessThanOrEqual(1)
  if(width===390||width===1440)await page.screenshot({path:info.outputPath(`profile-${width}.png`),fullPage:true})
 }
 await page.getByRole('button',{name:'登录与安全',exact:true}).click()
 await expect(page.getByRole('button',{name:'绑定微信',exact:true})).toBeDisabled()
 await expect(page.getByRole('button',{name:'绑定邮箱',exact:true})).toBeDisabled()
 const password=page.getByTestId('account-password');await password.locator('summary').click()
 async function fillPassword(current:string){
  await password.getByLabel('当前密码',{exact:true}).fill(current)
  await password.getByLabel('新密码',{exact:true}).fill('fixture-only-new-browser-password')
  await password.getByLabel('确认新密码',{exact:true}).fill('fixture-only-new-browser-password')
 }
 await fillPassword('wrong-fixture');await password.getByRole('button',{name:'确认修改密码并退出会话'}).click()
 await expect(page.getByRole('alert').filter({hasText:'当前密码不正确'})).toBeVisible()
 await expect(password.getByLabel('当前密码',{exact:true})).toHaveValue('')
 await fillPassword('fixture-only-browser-password');await password.getByRole('button',{name:'确认修改密码并退出会话'}).click()
 await expect(page.getByRole('heading',{name:'账户登录',exact:true})).toBeVisible()
 await expect(page.getByRole('status').filter({hasText:'密码已修改'})).toBeVisible()
 await page.getByLabel('账户',{exact:true}).fill('self-service-browser')
 await page.getByLabel('密码',{exact:true}).fill('fixture-only-new-browser-password')
 await page.getByRole('button',{name:'登录并进入总览'}).click()
 await expect(page.locator('.account-text')).toContainText('self-service-browser')
 await page.goto('/profile?section=security');const closure=page.getByTestId('account-closure');await closure.locator('summary').click()
 await expect(closure.getByRole('button',{name:'确认注销登录访问'})).toBeDisabled()
 await closure.getByLabel('验证当前密码',{exact:true}).fill('fixture-only-new-browser-password')
 await closure.getByLabel('输入“注销当前账户”',{exact:true}).fill('注销当前账户')
 await closure.getByRole('checkbox').check();await closure.getByRole('button',{name:'确认注销登录访问'}).click()
 await expect(page.getByRole('heading',{name:'账户登录',exact:true})).toBeVisible()
 await expect(page.getByRole('status').filter({hasText:'研究记录仍保留'})).toBeVisible()
 expect(errors).toEqual([])
})

test('login appearance and unavailable contact channels do not fake authentication',async({page},info)=>{
 const calls:string[]=[];page.on('request',r=>{if(r.method()==='POST')calls.push(new URL(r.url()).pathname)})
 await page.goto('/login');await page.getByRole('button',{name:'切换登录页明暗主题'}).click()
 await expect(page.locator('.auth-scene')).toHaveAttribute('data-auth-theme','light')
 for(const name of ['邮箱验证码','手机验证码','微信'])await expect(page.getByRole('button',{name,exact:true})).toBeDisabled()
 await page.screenshot({path:info.outputPath('login-light.png')})
 await page.getByRole('button',{name:'切换登录页明暗主题'}).click()
 await page.screenshot({path:info.outputPath('login-dark.png')});expect(calls).toEqual([])
})
