import {test,expect} from '@playwright/test'

test('real login, member creation, registration and logout do not expose a second market home', async ({page},info)=>{
  const errors:string[]=[]
  page.on('pageerror',e=>errors.push(e.message))
  await page.goto('/')
  await expect(page).toHaveURL(/\/login\?next=/)
  await expect(page.getByRole('heading',{name:'账户登录',exact:true})).toBeVisible()
  await expect(page.locator('iframe')).toHaveCount(0)
  await expect(page.locator('.workspace')).toHaveCount(0)
  await page.getByLabel('账户',{exact:true}).fill('browser-admin')
  await page.getByLabel('密码',{exact:true}).fill('test-only-browser-pass')
  await expect(page.getByLabel('密码',{exact:true})).toHaveAttribute('type','password')
  await page.getByRole('button',{name:'显示密码'}).click()
  await expect(page.getByLabel('密码',{exact:true})).toHaveAttribute('type','text')
  await page.getByRole('button',{name:'隐藏密码'}).click()
  await page.screenshot({path:info.outputPath('login.png')})
  await page.getByRole('button',{name:'登录并进入总览'}).click()
  await expect(page.getByRole('heading',{name:'市场总览',exact:true})).toBeVisible()
  await expect(page.locator('.sidebar')).toHaveCount(1)
  await page.goto('/profile')
  await expect(page.getByRole('heading',{name:'用户管理'})).toBeVisible()
  await page.getByLabel('新成员用户名',{exact:true}).fill('browser-member')
  await page.getByLabel('新成员密码',{exact:true}).fill('test-only-member-pass')
  await page.getByLabel('确认新成员密码',{exact:true}).fill('test-only-member-pass')
  await page.getByRole('button',{name:'创建成员账户'}).click()
  await expect(page.getByRole('status').filter({hasText:'成员账户已创建'})).toBeVisible()
  await expect(page.locator('.account-text')).toContainText('browser-admin')
  await page.getByTitle('退出登录', {exact:true}).click()
  await expect(page.getByRole('heading',{name:'账户登录',exact:true})).toBeVisible()
  await expect(page.locator('.workspace')).toHaveCount(0)
  await page.getByLabel('账户',{exact:true}).fill('browser-member')
  await page.getByLabel('密码',{exact:true}).fill('test-only-member-pass')
  await page.getByRole('button',{name:'登录并进入总览'}).click()
  await page.goto('/profile')
  await expect(page.locator('.account-text')).toContainText('browser-member')
  await expect(page.getByRole('heading',{name:'用户管理'})).toHaveCount(0)
  expect((await page.request.get('/api/admin/users')).status()).toBe(403)
  await page.getByTitle('退出登录', {exact:true}).click()
  await page.getByRole('link',{name:'创建账户',exact:true}).click()
  await expect(page).toHaveURL(/\/register/)
  await page.getByLabel('账户',{exact:true}).fill('browser-registered')
  await page.getByLabel('密码',{exact:true}).fill('test-only-register-pass')
  await page.getByLabel('确认密码',{exact:true}).fill('test-only-register-pass')
  await page.getByLabel('邀请码',{exact:true}).fill('browser-test-invite')
  await page.getByRole('button',{name:'创建账户并进入总览'}).click()
  await expect(page.locator('.account-text')).toContainText('browser-registered')
  expect((await page.request.get('/api/auth/me')).ok()).toBeTruthy()
  expect(errors).toEqual([])
})
