import {test,expect} from '@playwright/test'
test('API profiles save encrypted without calling a model; tiers and account removal are reversible',async({page},info)=>{
 const writes:string[]=[];const errors:string[]=[]
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.url().match(/\/profiles\/[^/]+\/(test|run)/))writes.push(r.url())})
 await page.goto('/login');await page.getByLabel('账户',{exact:true}).fill('browser-admin');await page.getByLabel('密码',{exact:true}).fill('test-only-browser-pass')
 await page.getByRole('button',{name:'登录并进入总览'}).click();await expect(page.locator('.account-text')).toContainText('browser-admin')
 await page.goto('/settings')
 const manager=page.getByTestId('ai-profile-manager')
 await manager.getByRole('button',{name:'新增模型配置'}).click()
 await manager.getByLabel('模型名称',{exact:true}).fill('test-model-no-calls')
 await manager.getByLabel('模型 API Key',{exact:true}).fill('fixture-key-browser-only')
 await manager.getByRole('button',{name:'加密保存配置'}).click()
 await expect(manager.getByRole('status')).toContainText('尚未调用模型')
 await manager.getByRole('button',{name:'设为共用默认'}).click()
 await expect(manager.getByRole('status')).toContainText('共用默认')
 expect(writes).toEqual([])
 const data=await(await page.request.get('/api/workspace/ai/profiles')).text()
 expect(data).not.toContain('fixture-key-browser-only');expect(data).not.toContain('ciphertext')
 await page.screenshot({path:info.outputPath('v104-ai-profiles.png'),fullPage:true})
 await page.goto('/profile')
 await page.getByLabel('新成员用户名',{exact:true}).fill('browser-tier-member')
 await page.getByLabel('新成员密码',{exact:true}).fill('test-only-tier-member-pass')
 await page.getByLabel('确认新成员密码',{exact:true}).fill('test-only-tier-member-pass')
 await page.getByRole('button',{name:'创建成员账户'}).click()
 await expect(page.getByRole('status').filter({hasText:'成员账户已创建'})).toBeVisible()
 const row=page.locator('tr').filter({has:page.getByRole('cell',{name:'browser-tier-member',exact:true})})
 await expect(row).toBeVisible()
 page.on('dialog',d=>d.accept())
 await row.getByRole('button',{name:'设为Plus'}).click();await expect(row.getByRole('cell',{name:'Plus',exact:true})).toBeVisible()
 await row.getByRole('button',{name:'移除账户'}).click();await expect(row).toContainText('已移除')
 await row.getByRole('button',{name:'恢复账户'}).click();await expect(row).toContainText('正常')
 await page.screenshot({path:info.outputPath('v104-members.png'),fullPage:true})
 expect(errors).toEqual([])
})
