"""Offline E-drive archive request/export/sign/verify; never auto-sync or delete.

The output parent and archive root must already be private. A separate 32-byte
archive key is explicitly supplied for response/verify, never discovered from
Codex, AI profiles or environment variables. No key is generated by this tool.
"""
from __future__ import annotations
import argparse
import os
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / 'backend'))
from app.workspace.archive_protocol import (canonical, decode, new_request, pack, unpack,
                                             MAX_PACKET_BYTES)
from app.workspace.archive_store import bounded_read, private_path, read_export


def publish(path, value):
    path = Path(path).absolute()
    private_path(path.parent, directory=True)
    with os.fdopen(os.open(path, os.O_CREAT | os.O_EXCL | os.O_WRONLY, 0o600), 'wb') as stream:
        stream.write(value)
    if os.name == 'nt':
        from app.workspace.bridge_runtime import windows_private_directory
        windows_private_directory(path, created=True, directory=False)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    commands = parser.add_subparsers(dest='command', required=True)
    req = commands.add_parser('request')
    req.add_argument('--code', required=True); req.add_argument('--start', required=True)
    req.add_argument('--end', required=True); req.add_argument('--output', required=True, type=Path)
    for action in ('respond','verify','parquet'):
        sub = commands.add_parser(action)
        sub.add_argument('--request', required=True, type=Path)
        if action != 'parquet': sub.add_argument('--key-file', required=True, type=Path)
        if action == 'verify': sub.add_argument('--packet', required=True, type=Path)
        else:
            sub.add_argument('--root', required=True, type=Path)
            sub.add_argument('--archive-id', required=True)
        if action == 'respond':
            sub.add_argument('--format', choices=('jsonl','parquet'), default='jsonl')
            sub.add_argument('--output', required=True, type=Path)
        if action == 'parquet': sub.add_argument('--new-archive-id', required=True)
    args = parser.parse_args()
    try:
        if args.command == 'request':
            value = new_request(args.code, args.start, args.end)
            publish(args.output, canonical(value))
            result = {'status':'request_created','request_id':value['request_id']}
        else:
            value = decode(bounded_read(args.request, 16384))
            if args.command == 'parquet':
                from app.workspace.archive_parquet import write
                rows = read_export(args.root, args.archive_id, value)
                output = write(args.root, args.new_archive_id, value, rows)
                result = {'status':'exported','rows':output['row_count'],'sha256':output['sha256']}
            else:
                private_path(args.key_file.parent, directory=True)
                key = bounded_read(args.key_file, 32)
                if args.command == 'respond':
                    if args.format == 'parquet':
                        from app.workspace.archive_parquet import read as reader
                    else: reader = read_export
                    rows = reader(args.root, args.archive_id, value)
                    publish(args.output, pack(value, rows, key))
                    result = {'status':'packet_written','rows':len(rows),'request_id':value['request_id']}
                else:
                    result = unpack(value, bounded_read(args.packet, MAX_PACKET_BYTES), key)
                    result.pop('rows')  # no full market rows or filesystem paths in console logs
        print(canonical({**result,'provider_called':False,'database_written':False,'actionable':False}).decode())
        return 0
    except (OSError, ValueError, ImportError) as exc:
        print(canonical({'status':'failed','reason':type(exc).__name__,'actionable':False}).decode())
        return 2


if __name__ == '__main__':
    raise SystemExit(main())
