import { test, expect } from '@playwright/test'

test('original report lives in home; ETF navigation preserves shell and filter', async ({ page }, info) => {
  const errors: string[] = [], forbidden: string[] = []
  page.on('pageerror', e => errors.push(e.message))
  page.on('request', r => { if (r.method() === 'POST') forbidden.push(r.url()) })
  await page.goto('/')
  await expect(page.getByRole('heading', {name:'市场总览',exact:true})).toBeVisible()
  await expect(page.getByRole('heading', {name:'行业与概念板块'})).toBeVisible()
  const report = page.frameLocator('iframe[title="原版 ETF 决策快照"]')
  await expect(report.locator('.decision-data-row').first()).toBeVisible()
  await report.locator('#horizonSelect').selectOption('5')
  await report.locator('#searchInput').fill('512480')
  await expect(report.locator('.decision-data-row')).toHaveCount(1)
  await expect(report.locator('.decision-data-row')).toContainText('512480')
  await page.screenshot({path:info.outputPath('original-template-home.png'),fullPage:true})
  await page.locator('.sidebar').evaluate(el => el.setAttribute('data-preserved-shell','yes'))
  await report.locator('.decision-data-row').click()
  await expect(page).toHaveURL(/\/etf\/512480.SH$/)
  await expect(page.locator('.sidebar')).toHaveAttribute('data-preserved-shell','yes')
  await expect(page.getByTestId('etf-chart')).toBeVisible()
  await page.goBack()
  await expect(page).toHaveURL(/\/$/)
  await expect(report.locator('#searchInput')).toHaveValue('512480')
  await expect(report.locator('#horizonSelect')).toHaveValue('5')
  await expect(report.locator('.decision-data-row')).toHaveCount(1)
  await expect(page.locator('.sidebar')).toHaveAttribute('data-preserved-shell','yes')
  expect(errors).toEqual([])
  expect(forbidden).toEqual([])
})

test('industry and concept remain visible without decision snapshots', async ({page}) => {
  await page.route('**/api/decision-board?*', r => r.fulfill({json:{rows:[],counts:{},horizons:[1,3,5,10]}}))
  await page.goto('/')
  await expect(page.getByRole('heading',{name:'行业与概念板块'})).toBeVisible()
  await page.getByRole('button',{name:'概念板块',exact:true}).click()
  await expect(page.locator('#market-boards')).toContainText('个板块')
  await page.goto('/boards')
  await expect(page).toHaveURL(/\/#market-boards$/)
  await expect(page.locator('.sidebar')).toHaveCount(1)
})

test('market context cards expose persisted history and catalog rows open the same detail route', async ({page}) => {
  await page.goto('/')
  await expect(page.locator('.market-context-card').first()).toBeVisible()
  await page.locator('.market-context-card').first().click()
  await expect(page.locator('.market-context-detail')).toBeVisible()

  await page.goto('/analysis?q=512480')
  const row = page.locator('tbody tr').first()
  await expect(row).toBeVisible()
  const detailCode = await row.locator('a').first().getAttribute('href')
  await row.click()
  await expect(page).toHaveURL(new RegExp(`${detailCode?.replace('.', '\\.').replace('/', '\\/')}$`))
})
