import { test, expect } from '@playwright/test'
import fs from 'node:fs/promises'
const code = '512480.SH'
test('overview → search four actions → chart; navigation alone does not call models', async ({ page }, info) => {
  const errors: string[] = [], writes: string[] = []
  page.on('pageerror', e => errors.push(e.message))
  page.on('request', r => { if (r.method() === 'POST' && r.url().includes('/research-jobs')) writes.push(r.url()) })
  await page.goto('/')
  await expect(page.getByRole('heading', { name: '市场总览', exact: true })).toBeVisible()
  await expect(page.locator('tbody tr').first()).toBeVisible()
  await page.screenshot({ path: info.outputPath('overview.png'), fullPage: true })
  const search = page.getByRole('combobox', { name: '搜索 ETF 或 LOF' })
  await search.fill(code)
  const results = page.getByRole('region', { name: '基金搜索结果' })
  await expect(results.getByRole('button', { name: '看图', exact: true })).toBeVisible()
  await expect(results.getByRole('button', { name: '录入持仓' })).toBeVisible()
  await expect(results.getByRole('button', { name: 'AI 草稿' })).toBeVisible()
  await results.getByRole('button', { name: /加自选|已自选/ }).click()
  await expect(results.getByRole('button', { name: '已自选' })).toBeDisabled()
  await results.getByRole('button', { name: 'AI 草稿' }).click()
  await expect(page).toHaveURL(/\/ai\?code=512480.SH/)
  await expect(page.getByLabel('AI 研究基金代码')).toHaveValue(code)
  expect(writes).toEqual([])
  await page.goto(`/etf/${code}`)
  await expect(page.getByTestId('etf-chart').locator('canvas').first()).toBeVisible()
  await expect(page.getByTestId('chart-indicators')).toContainText('MACD_HIST')
  await expect(page.getByText('图表初始化失败', { exact: false })).toHaveCount(0)
  const chart = page.getByTestId('etf-chart'); await chart.hover(); await page.mouse.wheel(0, -300)
  const box = (await chart.boundingBox())!; await page.mouse.move(box.x + 250, box.y + 100); await page.mouse.down(); await page.mouse.move(box.x + 400, box.y + 100, { steps: 8 }); await page.mouse.up()
  await page.getByTestId('chart-reset').click(); await chart.dblclick({ position: { x: 150, y: 90 } })
  await page.screenshot({ path: info.outputPath('detail.png'), fullPage: true })
  await page.getByRole('button', { name: '30 分钟', exact: true }).click()
  await expect(page.getByRole('heading', { name: '该周期暂无合格数据' })).toBeVisible()
  expect(errors).toEqual([])
})

test('holding preview is not a write; confirm, cost context and undo are usable', async ({ page, request }, info) => {
  const before = (await (await request.get('/api/workspace/holdings')).json()).items.find((r: any) => r.ts_code === code)
  await page.goto(`/holdings?code=${code}`)
  await expect(page.locator('[name=holding-code]')).toHaveValue(code)
  await page.locator('[name=holding-shares]').fill('1234')
  await page.locator('[name=holding-cost]').fill('4.551')
  await page.getByRole('button', { name: '生成录入预览' }).click()
  await expect(page.getByTestId('import-preview')).toBeVisible()
  const current = (await (await request.get('/api/workspace/holdings')).json()).items.find((r: any) => r.ts_code === code)
  expect(current?.shares).toBe(before?.shares)
  page.on('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '确认导入 1 条' }).click()
  await expect(page.getByRole('button', { name: '撤销这次导入' })).toBeVisible()
  const after = (await (await request.get('/api/workspace/holdings')).json()).items.find((r: any) => r.ts_code === code)
  expect(after.shares).toBe(1234); expect(after.cost_price).toBe(4.551)
  await page.screenshot({ path: info.outputPath('holdings.png'), fullPage: true })
  const other = await page.context().newPage(); await other.goto(`/etf/${code}`)
  await expect(other.getByTestId('etf-chart').locator('canvas').first()).toBeVisible()
  await expect(other.getByTestId('chart-cost-label')).toContainText('4.551')
  await other.screenshot({ path: info.outputPath('cost-line.png'), fullPage: true }); await other.close()
  await page.getByRole('button', { name: '撤销这次导入' }).click()
  await expect(page.getByText('导入已撤销。', { exact: true })).toBeVisible()
  const reverted = (await (await request.get('/api/workspace/holdings')).json()).items.find((r: any) => r.ts_code === code)
  expect(reverted?.shares).toBe(before?.shares)
  await page.getByRole('button', { name: '复制为新预览', exact: true }).click()
  await expect(page.getByRole('button', { name: '确认导入 1 条' })).toBeVisible()
  await page.getByRole('button', { name: '取消预览', exact: true }).click()
})

test('research result import remains a candidate, is plain text and requires review', async ({ page, request }, info) => {
  await page.goto(`/ai?code=${code}`)
  await page.getByRole('button', { name: '建立证据包与任务' }).click()
  await expect(page.getByRole('button', { name: '导出证据包' })).toBeVisible()
  const jobs = await (await request.get(`/api/workspace/research-jobs?code=${code}`)).json()
  const job = jobs.items[0]
  const exported = await (await request.get(`/api/workspace/research-jobs/${job.job_id}/export`)).json()
  const evidence = exported.bundle.evidence[0].id
  const result = { schema_version: 'etf-research-result-v1', job_id: job.job_id, input_hash: job.input_hash, producer: 'manual', producer_version: 'browser-fixture', model: 'none', summary: '浏览器测试候选，不是真实模型分析', facts: [{ text: '这是一份带固定引用的演示研究记录。', evidence_ids: [evidence] }], inferences: [], risks: [], conflicts: [], limitations: ['Mock 数据；没有调用任何真实模型。'], evidence_ids: [evidence], report_markdown: '<img src=x onerror="window.fakeReportExecuted=true">测试报告以纯文本展示' }
  await page.locator('input[type=file][accept=".json,application/json"]').setInputFiles({ name: 'result.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(result)) })
  await expect(page.getByRole('button', { name: '确认审核', exact: true })).toBeVisible()
  const candidate = await (await request.get(`/api/workspace/research-jobs/${job.job_id}`)).json(); expect(candidate.review_status).toBe('pending')
  await page.getByText('完整报告（安全纯文本展示）', { exact: true }).click()
  await expect(page.getByTestId('research-report-text')).toContainText('<img src=x')
  expect(await page.evaluate(() => (window as any).fakeReportExecuted)).toBeUndefined()
  page.on('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '确认审核', exact: true }).click()
  await expect(page.getByRole('button', { name: '确认审核', exact: true })).toHaveCount(0)
  const reviewed = await (await request.get(`/api/workspace/research-jobs/${job.job_id}`)).json(); expect(reviewed.review_status).toBe('accepted'); expect(reviewed.actionable).toBe(false)
  await page.screenshot({ path: info.outputPath('research.png'), fullPage: true })
})

test('mobile drawer, bookmarked routes and honest 404s', async ({ page, request }, info) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await expect(page.getByRole('button', { name: '打开导航', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '打开导航', exact: true }).click()
  await expect(page.locator('.workspace')).toHaveClass(/mobile-open/)
  await page.screenshot({ path: info.outputPath('mobile.png'), fullPage: true })
  await page.locator('aside').getByRole('link', { name: '我的自选', exact: true }).click()
  await expect(page.locator('.workspace')).not.toHaveClass(/mobile-open/)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.goto('/legacy#holdings')
  await expect(page).toHaveURL(/\/holdings$/)
  expect((await request.get('/api/workspace/does-not-exist')).status()).toBe(404)
  expect((await request.get('/workspace-assets/missing.js')).status()).toBe(404)
})
