import {test,expect} from '@playwright/test'

test('calendar candles and fullscreen leave a path back when hourly data is missing',async({page,request},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 const daily=await(await request.get('/api/workspace/instruments/512480.SH/chart?interval=1d&limit=500')).json()
 const week=await(await request.get('/api/workspace/instruments/512480.SH/chart?interval=1w&limit=500')).json()
 expect(week.interval).toBe('1w');expect(week.bars.length).toBeLessThan(daily.bars.length)
 expect(week.bars.some((r:any)=>r.source_bar_count>1)).toBeTruthy()
 await page.goto('/etf/512480.SH')
 await page.getByRole('button',{name:'周 K',exact:true}).click()
 await expect(page.getByRole('button',{name:'周 K',exact:true})).toHaveAttribute('aria-pressed','true')
 await expect(page.getByTestId('etf-chart').locator('canvas').first()).toBeVisible()
 await page.getByRole('button',{name:'月 K',exact:true}).click()
 await expect(page.getByRole('button',{name:'月 K',exact:true})).toHaveAttribute('aria-pressed','true')
 await page.getByTestId('chart-fullscreen').click();await expect(page.locator('.expanded-chart')).toBeVisible()
 await page.keyboard.press('Escape');await expect(page.locator('.expanded-chart')).toHaveCount(0)
 await page.getByRole('button',{name:'打开全部',exact:true}).click()
 await expect(page.getByText('图表初始化失败',{exact:false})).toHaveCount(0)
 await page.screenshot({path:info.outputPath('v104-month-chart.png'),fullPage:true})
 await page.getByRole('button',{name:'小时 K',exact:true}).click()
 await expect(page.getByRole('heading',{name:'该周期暂无合格数据'})).toBeVisible()
 await page.getByRole('button',{name:'日 K',exact:true}).click()
 await expect(page.getByTestId('etf-chart').locator('canvas').first()).toBeVisible()
 expect(errors).toEqual([])
})

test('sector alias searches retain original home and show the matching basis',async({page},info)=>{
 await page.goto('/analysis?q='+encodeURIComponent('元器件'))
 await expect(page.getByText('关联词：',{exact:false})).toBeVisible()
 await expect(page.locator('tbody')).toContainText('512480')
 await page.goto('/')
 const frame=page.frameLocator('iframe[title="原版 ETF 决策快照"]')
 await frame.locator('#horizonSelect').selectOption('20')
 await frame.locator('#searchInput').fill('512480')
 await expect(frame.locator('.decision-data-row')).toHaveCount(1)
 await expect(frame.locator('button[data-favorite]').first()).toHaveText(/[★☆]/)
 await expect(frame.locator('.decision-table th').filter({hasText:'较昨日'})).toHaveCount(0)
 await page.screenshot({path:info.outputPath('v104-original-template.png'),fullPage:true})
})

test('news age, factor instructions and AI steps are visible without model requests',async({page},info)=>{
 const writes:string[]=[];page.on('request',r=>{if(r.method()==='POST')writes.push(r.url())})
 await page.goto('/research/news')
 await expect(page.getByRole('heading',{name:'新闻采集与时间',exact:true})).toBeVisible()
 await page.getByLabel('发布时间',{exact:true}).selectOption('24')
 await page.goto('/factors');await expect(page.getByText('使用方法：',{exact:false})).toBeVisible()
 await page.goto('/ai');await page.getByRole('button',{name:'本地 Codex',exact:true}).click()
 await expect(page.getByTestId('ai-setup-guide')).toContainText('--max-jobs 1')
 await page.screenshot({path:info.outputPath('v104-ai-steps.png'),fullPage:true})
 expect(writes).toEqual([])
})
