<script setup lang="ts">
import {computed,ref} from 'vue'
import {useRoute} from 'vue-router'
import {useQuery} from '../lib/query'
import {useVisibleRefresh} from '../lib/useVisibleRefresh'
import {num,pct,direction,stamp,levelPrice,record,numeric} from '../lib/format'
import type {Detail,ChartData,SupportLevel} from '../lib/types'
import PageState from '../components/PageState.vue'
import Badge from '../components/Badge.vue'
import EtfChart from '../components/EtfChart.vue'
import OutlookPanel from '../components/OutlookPanel.vue'
import ResearchPanel from '../components/ResearchPanel.vue'
import FavoriteButton from '../components/FavoriteButton.vue'
import HistoryLoader from '../components/HistoryLoader.vue'
import IndicatorReadings from '../components/IndicatorReadings.vue'
const route=useRoute(),code=computed(()=>String(route.params.code??'').toUpperCase()),interval=ref('1d'),tab=ref(route.query.tab==='ai'?'ai':'chart')
const q=useQuery<Detail>(()=>'/api/workspace/instruments/'+encodeURIComponent(code.value)),chart=useQuery<ChartData>(()=>'/api/workspace/instruments/'+encodeURIComponent(code.value)+'/chart?interval='+interval.value+'&limit=500')
useVisibleRefresh(()=>Promise.all([q.refresh(),chart.refresh()]))
const sr=computed(()=>chart.data.value?.support_resistance??q.data.value?.support_resistance)
const entry=computed(()=>record(q.data.value?.decision?.entry_exit_ref))
const themeRank=computed(()=>record(q.data.value?.decision?.theme_relative_strength))
function zoneText(level:SupportLevel|number|null|undefined){
  const rec=record(level)
  const low=numeric(rec.zone_low), high=numeric(rec.zone_high)
  if(low!=null&&high!=null&&low!==high) return `${num(low,3)}–${num(high,3)}`
  return num(levelPrice(level as SupportLevel),3)
}
function distance(value:unknown){const p=typeof value==='number'?value:null;return p!=null&&q.data.value?.quote.price? p/q.data.value.quote.price-1:null}
</script>
<template><PageState :loading="q.loading.value" :error="q.error.value" :empty="!q.data.value" @retry="q.reload"><template v-if="q.data.value"><div class="page-heading"><div><p class="eyebrow">{{q.data.value.instrument.kind}} / {{code}} / {{q.data.value.instrument.theme_l1}}</p><h1>{{q.data.value.instrument.name}} <span class="grade" :data-grade="q.data.value.decision?.grade">{{q.data.value.decision?.grade??'数据异常'}}</span></h1><p>决策快照 {{stamp(q.data.value.decision_time)}} · 指标 {{q.data.value.indicator_as_of??'缺失'}}</p></div><div class="heading-actions"><FavoriteButton :code="code"/><RouterLink class="button" :to="{path:'/holdings',query:{code}}">录入持仓</RouterLink><button class="button primary" @click="tab='ai'">AI 研究</button></div></div><div v-if="q.data.value.quote.is_mock||q.data.value.quote.status==='mock'" class="notice warning-notice" role="status">演示/Mock 报价，不可操作。</div>
 <p class="small-note" data-testid="detail-freshness">报价源时间 {{q.data.value.quote.source_time??'未知'}} · 抓取 {{q.data.value.quote.fetched_at??'未知'}} · 指标截至 {{q.data.value.indicator_as_of??'未知'}} · 快照 {{q.data.value.snapshot_id??'未生成'}} · K线源日期 {{chart.data.value?.source_as_of??'未知'}} · 读取时点 {{chart.data.value?.as_of??'未知'}} · 计算完成 {{chart.data.value?.computed_at??'未知'}} · 价格基准 {{chart.data.value?.adjust??'未知'}} · 指标口径 {{chart.data.value?.indicator_basis??'未知'}}</p>
 <div v-if="q.data.value.history_issue" class="notice warning-notice" role="status">历史资格阻断：{{q.data.value.history_issue}}。原始 K 线未改写。</div>
<div v-if="['stale','degraded','unverified','historical_close'].includes(String(q.data.value.quote.status))" class="notice" role="status">报价状态 {{q.data.value.quote.status}}，不是实时可操作行情。</div>
<div class="cards"><article class="stat-card"><div class="label">最后观测价格<Badge :value="q.data.value.quote.status"/></div><div class="value" :class="direction(q.data.value.quote.change_ratio)">{{num(q.data.value.quote.price,3)}}<span class="delta">{{pct(q.data.value.quote.change_ratio)}}</span></div><small>{{stamp(q.data.value.quote.source_time)}} · {{q.data.value.quote.source??'无报价'}}</small></article><article class="stat-card"><div class="label">支撑带 · 聚类价格区</div><div class="value">{{zoneText(sr?.nearest_support)}}</div><small>相对现价 {{pct(distance(levelPrice(sr?.nearest_support)))}} · {{String(entry.position??'unknown')}}</small></article><article class="stat-card"><div class="label">压力带 · 聚类价格区</div><div class="value">{{zoneText(sr?.nearest_resistance)}}</div><small>相对现价 {{pct(distance(levelPrice(sr?.nearest_resistance)))}} · {{String(themeRank.label??'主题相对强弱不足')}}</small></article><article class="stat-card"><div class="label">我的每份成本</div><div class="value">{{num(q.data.value.holding?.cost_price,3)}}</div><small>持仓盈亏 <span :class="direction(q.data.value.holding?.pnl_ratio)">{{pct(q.data.value.holding?.pnl_ratio)}}</span> · 未录入不估算</small></article></div><div class="section-tabs"><button :class="{active:tab==='chart'}" @click="tab='chart'">技术图表</button><button :class="{active:tab==='ai'}" @click="tab='ai'">AI 研究与证据</button></div><template v-if="tab==='chart'"><div class="card"><div class="card-header"><div><h2>K 线与技术指标</h2><p>统一 Python 公式 · 已确认日 K 支撑压力快照，与最新报价可能不同步</p></div></div><HistoryLoader :code="code" @updated="q.reload();chart.reload()"/><div v-if="!chart.data.value?.available" class="toolbar" aria-label="切换K线周期"><button class="button" v-for="p in [{id:'1d',name:'日 K'},{id:'1w',name:'周 K'},{id:'1mo',name:'月 K'},{id:'30m',name:'30 分钟'},{id:'60m',name:'小时 K'}]" :key="p.id" @click="interval=p.id">{{p.name}}</button></div><PageState :loading="chart.loading.value" :error="chart.error.value" :empty="!chart.data.value?.available" title="该周期暂无合格数据" :description="chart.data.value?.reason??'日线不会冒充分钟线；请检查数据同步状态。'" @retry="chart.reload"><EtfChart v-if="chart.data.value?.available" :data="chart.data.value" :cost="q.data.value.holding?.cost_price" allow-minutes @period="interval=$event"/></PageState></div><div v-if="chart.data.value?.core_snapshot_match===false||chart.data.value?.history_truncated" class="notice warning-notice">图表历史与最新指标快照未完全对齐或历史已截断，请核对数据版本；不能把它当作决策快照的精确历史回放。</div>
<div v-if="chart.data.value?.history_issue||chart.data.value?.qualification==='mock'" class="notice warning-notice">{{chart.data.value?.history_issue?`价格连续性/单位问题：${chart.data.value.history_issue}`:'图表来源为 Mock'}}。未用于操作级信号。</div><div v-if="chart.data.value?.indicator_note" class="notice" role="status">{{chart.data.value.indicator_note}}</div><div v-if="q.data.value.holding&&!chart.data.value?.cost_overlay_allowed" class="notice">当前价格基准不允许直接叠加持仓成本线，避免复权口径混淆。</div><div class="card"><div class="card-header"><div><h2>指标快照数值</h2><p>{{q.data.value.indicator_version}} · {{q.data.value.indicator_as_of}} · 不由 AI 计算</p></div></div><div class="card-body"><IndicatorReadings :readings="chart.data.value?.studies?.readings??[]"/></div></div><div class="card"><div class="card-header"><div><h2>未来研究情景</h2><p>预测与真实 K 线分离；区间不代表承诺，历史频率不等于校准概率。</p></div></div><div class="card-body"><OutlookPanel :code="code" :forecasts="q.data.value.forecasts"/></div></div></template><ResearchPanel v-else :code="code"/></template></PageState></template>
