<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import { BriefcaseBusiness, Upload, Plus, RefreshCw, Undo2, Check, Trash2 } from 'lucide-vue-next'
import { api, downloadBlob, errorText } from '../lib/api'
import { useQuery } from '../lib/query'
import { compact, num, pct, direction, stamp, record } from '../lib/format'
import type { Holdings, ImportBatch } from '../lib/types'
import PageState from '../components/PageState.vue'
import Badge from '../components/Badge.vue'
const route = useRoute(), q = useQuery<Holdings>('/api/workspace/holdings'), history = useQuery<{ items: ImportBatch[] }>('/api/workspace/imports')
const code = ref(''), shares = ref(''), cost = ref(''), busy = ref(false), message = ref(''), error = ref(''), batch = ref<ImportBatch | null>(null), imageInput = ref<HTMLInputElement | null>(null)
const risk = ref<Record<string, unknown> | null>(null)
watch(() => [route.query.code, route.query.add], () => { code.value = String(route.query.code ?? route.query.add ?? '').toUpperCase() }, { immediate: true })
const selected = computed(() => batch.value?.candidates.filter(v => v.selected).length ?? 0)
async function act(work: () => Promise<void>) { if (busy.value) return; busy.value = true; error.value = ''; message.value = ''; try { await work() } catch (e) { error.value = errorText(e) } finally { busy.value = false } }
async function manual() { await act(async () => { batch.value = await api<ImportBatch>('/api/workspace/imports/preview-rows', { method: 'POST', body: { candidates: [{ row_index: 1, ts_code: code.value.trim().toUpperCase(), shares: shares.value, cost_price: cost.value, selected: true }] } }); message.value = '已生成候选。请核对每份成本与份额，尚未写入持仓。' }) }
async function fileChange(event: Event, image = false) { const input = event.target as HTMLInputElement, file = input.files?.[0]; if (!file) return; input.value = ''; await act(async () => { if (file.size > (image ? 10 : 2) * 1024 * 1024) throw new Error('oversize'); const data = new FormData(); data.append('file', file); if (image) { const ocr = await api<{ session_id: string }>('/api/holding-imports', { method: 'POST', body: data, timeout: 90000 }); batch.value = await api<ImportBatch>(`/api/workspace/imports/from-ocr/${ocr.session_id}`, { method: 'POST' }) } else batch.value = await api<ImportBatch>('/api/workspace/imports/preview', { method: 'POST', body: data }); message.value = '识别/解析结果仅为候选，请逐项修正并保存核验。'; await history.reload() }) }
async function saveCandidates() { if (!batch.value) return; const b = batch.value; batch.value = await api<ImportBatch>(`/api/workspace/imports/${b.batch_id}`, { method: 'PATCH', body: { expected_hash: b.candidate_hash, candidates: b.candidates.map(c => ({ row_index: c.row_index, ts_code: c.ts_code, shares: c.shares, cost_price: c.cost_price, selected: c.selected })) } }) }
async function confirm() { if (!batch.value || !window.confirm(`确认使用 ${selected.value} 条选中候选覆盖对应基金的当前份额和每份成本？这不是交易指令。`)) return; await act(async () => { await saveCandidates(); const b = batch.value!; batch.value = await api<ImportBatch>(`/api/workspace/imports/${b.batch_id}/confirm`, { method: 'POST', body: { expected_hash: b.candidate_hash } }); message.value = '持仓已更新。后续编辑发生前可撤销本次导入。'; await q.reload(); await history.reload() }) }
async function undo(id: string) { if (!window.confirm('撤销这批导入？若持仓已被再次修改，系统会阻止覆盖。')) return; await act(async () => { batch.value = await api<ImportBatch>(`/api/workspace/imports/${id}/undo`, { method: 'POST' }); await q.reload(); await history.reload(); message.value = '导入已撤销。' }) }
async function cancel() { if (!batch.value) return; await act(async () => { await api(`/api/workspace/imports/${batch.value!.batch_id}/cancel`, { method: 'POST' }); batch.value = null; await history.reload() }) }
async function remove(c: string) { if (!window.confirm(`从个人持仓移除 ${c}？不执行任何卖出。`)) return; await act(async () => { await api(`/api/holdings/${c}`, { method: 'DELETE' }); await q.reload() }) }
async function loadBatch(id: string) { await act(async () => { batch.value = await api<ImportBatch>(`/api/workspace/imports/${id}`) }) }
function template() { downloadBlob(new Blob(['\ufeff基金代码,份额,每份成本\n512480.SH,100,1.000\n'], { type: 'text/csv;charset=utf-8' }), 'holding-template.csv') }
async function inspectRisk() { await act(async () => { risk.value = await api<Record<string, unknown>>('/api/workspace/portfolio-risk') }) }
</script>
<template>
<div class="page-heading"><div><span class="eyebrow">PERSONAL PORTFOLIO</span><h1>我的持仓</h1><p>基金技术状态与个人成本，始终分开判断。</p></div><div class="heading-actions"><button class="button" @click="q.reload"><RefreshCw :size="15"/>刷新持仓</button><button class="button" @click="template">导入模板</button></div></div>
<div v-if="message" class="notice" role="status">{{ message }}</div><div v-if="error" class="form-error" role="alert">{{ error }}</div>
<PageState :loading="q.loading.value" :error="q.error.value" @retry="q.reload"><template v-if="q.data.value"><div class="cards"><div class="stat-card"><small>已录入持仓市值</small><div class="value">{{ compact(q.data.value.total_market_value) }}</div><p>缺失行情时不以成本价代替</p></div><div class="stat-card"><small>持仓基金</small><div class="value">{{ q.data.value.items.length }}<em>只</em></div><p>只包含当前账户</p></div><div class="stat-card"><small>尚未取得价格</small><div class="value">{{ q.data.value.unpriced_count }}<em>只</em></div><p>权重不包含未录入的现金</p></div><div class="stat-card"><small>组合风险上下文</small><button class="button" :disabled="busy" @click="inspectRisk">查看集中度与相关性</button><p>不是共享市场信号</p></div></div>
<div class="card section"><div class="card-header"><h2><BriefcaseBusiness :size="17"/>持仓明细</h2><small>成本与份额均为人工确认记录</small></div><div v-if="!q.data.value.items.length" class="empty-inline">尚未录入持仓。可在下方手工录入、导入表格，或识别截图。</div><div v-else class="table-scroll"><table><thead><tr><th>基金</th><th class="numeric">份额 / 每份成本</th><th class="numeric">价格 / 浮动盈亏</th><th class="numeric">持仓权重</th><th>当前研究动作</th><th>来源</th><th></th></tr></thead><tbody><tr v-for="row in q.data.value.items" :key="row.ts_code"><td class="name-cell"><RouterLink :to="`/etf/${row.ts_code}`">{{ row.name }}</RouterLink><small>{{ row.ts_code }} · {{ row.theme }}</small></td><td class="numeric">{{ num(row.shares, 2) }}<small>{{ num(row.cost_price, 4) }}</small></td><td class="numeric">{{ num(row.quote.price, 3) }}<small :class="direction(row.pnl)">{{ num(row.pnl, 2) }} / {{ pct(row.pnl_ratio) }}</small></td><td class="numeric">{{ pct(row.weight) }}</td><td><span class="grade" :data-grade="row.grade">{{ row.grade }}</span></td><td><Badge :value="row.quote.status"/><small>{{ stamp(row.quote.source_time) }}</small></td><td><button class="icon-button" :aria-label="`移除 ${row.name}`" :disabled="busy" @click="remove(row.ts_code)"><Trash2 :size="14"/></button></td></tr></tbody></table></div><div class="table-footer">{{ q.data.value.data_warning }}</div></div></template></PageState>
<div v-if="risk" class="card section"><div class="card-header"><h2>个人风险上下文</h2><button class="text-button" @click="risk = null">收起</button></div><div class="card-body"><dl class="details-list"><dt>最大单只权重</dt><dd>{{ pct(typeof risk.max_weight === 'number' ? risk.max_weight : null) }}</dd><dt>定价完整</dt><dd>{{ risk.pricing_complete ? '是' : '否：存在缺失价格' }}</dd></dl><p class="small-note">主题与收益相关不等于底层成分持仓重叠；这里不生成调仓指令。</p><pre class="report-text">{{ JSON.stringify(risk.correlations ?? [], null, 2) }}</pre><p class="small-note">{{ Array.isArray(risk.limitations) ? risk.limitations.join('；') : '' }}</p></div></div>
<div class="card section"><div class="card-header"><h2><Plus :size="17"/>录入与导入</h2><small>所有途径先预览，确认后才写入</small></div><div class="card-body"><form class="form-grid" @submit.prevent="manual"><label class="field">场内 ETF / LOF 代码<input v-model="code" name="holding-code" autocomplete="off" required placeholder="512480.SH" maxlength="32"></label><label class="field">持有份额<input v-model="shares" name="holding-shares" inputmode="decimal" required placeholder="例如 1000"></label><label class="field">每份成本（不是总成本）<input v-model="cost" name="holding-cost" inputmode="decimal" required placeholder="例如 1.253"></label><div class="actions"><button class="button primary" :disabled="busy">生成录入预览</button></div></form><div class="divider"/><div class="form-grid"><label class="field">CSV / XLSX 表格（最多 2 MB）<input class="file-input" type="file" accept=".csv,.xlsx" :disabled="busy" @change="fileChange($event)"></label><label class="field">持仓截图（本地 OCR）<input ref="imageInput" class="file-input" type="file" accept="image/png,image/jpeg,image/webp" :disabled="busy" @change="fileChange($event, true)"></label><p class="small-note">OCR 未配置或识别不完整时，请使用手工录入。不会在未授权时把图片发送给云端模型；不会自动猜测同主题基金。</p></div></div></div>
<div v-if="batch" class="card section" data-testid="import-preview"><div class="card-header"><h2>导入预览 <Badge :value="batch.status"/></h2><small>{{ stamp(batch.expires_at) }} 到期</small></div><div class="table-scroll"><table class="import-preview"><thead><tr><th>选择</th><th>基金代码</th><th>份额</th><th>每份成本</th><th>校验</th></tr></thead><tbody><tr v-for="row in batch.candidates" :key="row.row_index"><td><input v-model="row.selected" type="checkbox" :aria-label="`选择第${row.row_index}行`" :disabled="batch.status !== 'preview' || busy"></td><td><input v-model="row.ts_code" :aria-label="`第${row.row_index}行代码`" :disabled="batch.status !== 'preview' || busy"><small>{{ row.name }}</small></td><td><input v-model="row.shares" :aria-label="`第${row.row_index}行份额`" :disabled="batch.status !== 'preview' || busy"></td><td><input v-model="row.cost_price" :aria-label="`第${row.row_index}行每份成本`" :disabled="batch.status !== 'preview' || busy"></td><td><span v-if="!row.errors.length" class="muted">已校验</span><div v-for="e in row.errors" :key="e" class="error-text">{{ e }}</div></td></tr></tbody></table></div><div class="card-body"><p class="small-note">{{ batch.note }} 修改后请保存核验；重复基金与有错误的选中行不能确认。</p><div v-if="batch.status === 'preview'" class="actions"><button class="button" :disabled="busy" @click="act(saveCandidates)">保存候选并核验</button><button class="button primary" :disabled="busy || selected === 0" @click="confirm"><Check :size="15"/>确认导入 {{ selected }} 条</button><button class="button" :disabled="busy" @click="cancel">取消预览</button></div><button v-else-if="batch.status === 'confirmed'" class="button" :disabled="busy" @click="undo(batch.batch_id)"><Undo2 :size="14"/>撤销这次导入</button></div></div>
<div class="card section"><div class="card-header"><h2><Upload :size="17"/>导入记录</h2></div><div class="card-body"><PageState :loading="history.loading.value" :error="history.error.value" :empty="!history.data.value?.items.length" title="还没有导入记录" description="每一次预览与确认都会留下当前账户的记录。" @retry="history.reload"><div v-for="item in history.data.value?.items" :key="item.batch_id" class="list-row"><button class="text-button" @click="loadBatch(item.batch_id)">{{ item.source_kind }} · {{ item.candidates.length }} 条</button><Badge :value="item.status"/></div></PageState></div></div>
</template>
