<script setup lang="ts">
import { computed, ref } from 'vue'
import { RefreshCw, ExternalLink } from 'lucide-vue-next'
import { useQuery } from '../lib/query'
import { grades, num, pct, frequency, metricLabel, direction, stamp, olderThan } from '../lib/format'
import type { Overview, Metric, BoardRow } from '../lib/types'
import PageState from '../components/PageState.vue'
import Badge from '../components/Badge.vue'
const horizon = ref(1), filter = ref(''), text = ref(''), sort = ref('grade')
const q = useQuery<Overview>(() => `/api/workspace/overview?horizon=${horizon.value}&limit=500`)
const rows = computed(() => {
  const list = (q.data.value?.rows ?? []).filter(r => (!filter.value || r.grade === filter.value) && `${r.name} ${r.ts_code} ${r.theme_l1 ?? ''}`.includes(text.value.trim()))
  const rank = (r: BoardRow) => { const index = grades.indexOf(r.grade); return index < 0 ? 99 : index }
  return [...list].sort((a, b) => sort.value === 'today' ? (b.return_1d ?? -Infinity) - (a.return_1d ?? -Infinity) : sort.value === 'week' ? (b.return_5d ?? -Infinity) - (a.return_5d ?? -Infinity) : rank(a) - rank(b) || a.ts_code.localeCompare(b.ts_code))
})
function detail(m?: Metric) { return m ? Object.entries(m).filter(([key, value]) => !['label','kind','status'].includes(key) && typeof value === 'number').map(([key, value]) => `${key}: ${num(value, 4)}`).join(' · ') : '' }
const columns = [{ key: 'volume', title: '量能' }, { key: 'ma', title: 'MA 均线' }, { key: 'macd', title: 'MACD' }, { key: 'kdj', title: 'KDJ' }, { key: 'td', title: 'TD9' }, { key: 'rsi', title: 'RSI' }] as const
</script>
<template><section data-testid="etf-matrix"><div class="page-heading"><div><p class="eyebrow">ETF INDICATOR MATRIX</p><h1>ETF 指标总表</h1><p>保留原版五档分组与横向对比。这里读同一决策快照，不再生成第二套买卖结论。</p></div><div class="heading-actions"><a href="/classic/etf-board" class="button"><ExternalLink :size="14"/>打开原版面板</a><button class="button" @click="q.reload" :disabled="q.loading.value"><RefreshCw :size="14"/>重新读取</button></div></div>
<div class="notice"><span>快照 {{ stamp(q.data.value?.generated_at) }} · 仅跟踪 ETF/LOF 池，非全市场覆盖。</span><Badge :value="q.data.value?.contains_mock ? 'mock' : olderThan(q.data.value?.generated_at,480) ? 'stale' : 'research'"/></div>
<div class="card"><div class="toolbar matrix-grades"><button class="button small" :class="{primary: !filter}" @click="filter=''">全部 {{ q.data.value?.total ?? 0 }}</button><button v-for="grade in grades" :key="grade" class="button small" :class="{primary: filter===grade}" @click="filter=grade">{{ grade }} {{ q.data.value?.counts[grade] ?? 0 }}</button><button class="button small" @click="filter='数据异常'">数据异常</button></div>
<div class="toolbar"><input v-model="text" aria-label="筛选 ETF 总表" placeholder="代码、名称或行业"/><label>预测期限<select v-model.number="horizon"><option v-for="h in [1,3,5,10]" :key="h" :value="h">{{h}} 个交易日</option></select></label><label>排序<select v-model="sort"><option value="grade">五档研究状态</option><option value="today">当日涨幅</option><option value="week">近 5 日涨幅</option></select></label><RouterLink to="/settings" class="text-button">数据接入与后台任务 →</RouterLink></div>
<PageState :loading="q.loading.value" :error="q.error.value" :empty="!rows.length" title="暂无对应 ETF 快照" description="到设置中更新跟踪池行情；筛选与页面跳转不会启动抓取。" @retry="q.reload"><div class="table-scroll matrix-scroll"><table class="matrix-table"><thead><tr><th scope="col">ETF / 行业</th><th scope="col">五档状态</th><th scope="col" class="numeric">快照价格</th><th scope="col" class="numeric">当日涨跌</th><th scope="col" class="numeric">近 5 日</th><th scope="col" v-for="col in columns" :key="col.key">{{col.title}}</th><th scope="col">板块依据</th><th scope="col" class="numeric">{{horizon}}日情景收益</th><th scope="col" class="numeric">历史上涨频率</th><th scope="col">数据状态</th></tr></thead><tbody><tr v-for="row in rows" :key="row.ts_code"><td class="name-cell"><RouterLink :to="'/etf/'+row.ts_code">{{row.name}}</RouterLink><small>{{row.ts_code}} · {{row.theme_l1 ?? '未分类'}}</small></td><td><span class="grade" :data-grade="row.grade" :title="row.grade_reason">{{row.grade}}</span></td><td class="numeric">{{num(row.price,3)}}</td><td class="numeric" :class="direction(row.return_1d)">{{pct(row.return_1d)}}</td><td class="numeric" :class="direction(row.return_5d)">{{pct(row.return_5d)}}</td><td v-for="col in columns" :key="col.key" :title="detail(row[col.key])"><strong class="matrix-metric">{{metricLabel(row[col.key])}}</strong><small>{{detail(row[col.key]) || '详细数值见单只 ETF'}}</small></td><td :title="String(row.sector?.detail ?? '')">{{metricLabel(row.sector)}}</td><td class="numeric forecast">{{pct(row.forecasts?.[horizon]?.expected_return)}}</td><td class="numeric">{{frequency(row.forecasts?.[horizon])}}<small>n={{row.forecasts?.[horizon]?.sample_count ?? '—'}} · 未作资格提升</small></td><td><Badge :value="row.freshness"/><small>{{row.data_status}}</small></td></tr></tbody></table></div></PageState><div class="table-footer">显示 {{rows.length}} / {{q.data.value?.total ?? 0}} · 指标状态不是上涨概率 · TD9 为 setup 计数，非 TD13 · 原版入口持续保留</div></div></section></template>
<style scoped>
.matrix-scroll{max-height:72vh}.matrix-table{min-width:1800px}.matrix-table thead th{position:sticky;top:0;background:var(--surface,#14171c);z-index:2}.matrix-table .name-cell{min-width:175px}.matrix-table td small{display:block;max-width:200px;white-space:normal;font-size:10px;line-height:1.6;color:var(--muted,#99a3b4)}.matrix-metric{font-size:12px;font-weight:500}.matrix-grades{flex-wrap:wrap}
</style>
