<script setup lang="ts">
import { computed, ref } from 'vue'
import { Newspaper, RefreshCw, ExternalLink } from 'lucide-vue-next'
import { useQuery } from '../lib/query'
import { api,errorText } from '../lib/api'
import { useSession } from '../stores/session'
import TaskProgress from '../components/TaskProgress.vue'
import { record, stamp } from '../lib/format'
import PageState from '../components/PageState.vue'
import Badge from '../components/Badge.vue'
const session=useSession(),hours=ref(0),jobId=ref(''),busy=ref(false),message=ref('')
const health=useQuery<{sources:{source:string;count:number;latest_published_at:string;last_fetched_at:string;age_hours:number;freshness:string}[];note:string;task?:{status:string}}>('/api/workspace/news-status')
function ageHours(value:unknown){const n=Date.parse(String(value));return Number.isFinite(n)?Math.max(0,(Date.now()-n)/3600000):Infinity}
async function sync(){busy.value=true;try{const r=await api<{job:{job_id:string}}>('/api/workspace/data-jobs',{method:'POST',body:{task:'news',codes:[],request_key:crypto.randomUUID()}});jobId.value=r.job.job_id;message.value='已排入新闻采集队列，查看下面步骤；重读页面不等于采集新消息。'}catch(e){message.value=errorText(e)}finally{busy.value=false}}
const q = useQuery<Record<string, unknown>[]>('/api/news?limit=100'), filter = ref('')
const rows = computed(() => (q.data.value ?? []).filter(row => (!filter.value || `${row.title} ${row.summary}`.includes(filter.value))&&(!hours.value||ageHours(row.published_at)<=hours.value)))
function safeUrl(value: unknown) { try { const u = new URL(String(value)); return ['https:', 'http:'].includes(u.protocol) && !u.username && !u.password ? u.href : undefined } catch { return undefined } }
</script><template><div class="page-heading"><div><span class="eyebrow">NEWS & CATALYSTS</span><h1>新闻线索</h1><p>新闻事实、规则分类与模型推断分开保留；抓取时间不能代替首次公开时间。</p></div><button class="button" @click="q.reload"><RefreshCw :size="14"/>重新读取</button></div><p class="notice" v-if="message" role="status">{{message}}</p><section class="card section"><div class="card-header"><h2>新闻采集与时间</h2><button v-if="session.role==='admin'||!session.identifier" class="button primary" :disabled="busy" @click="sync">采集最新新闻 / RSS</button></div><div class="card-body"><p>{{health.data.value?.note}}</p><p v-for="source in health.data.value?.sources??[]" :key="source.source">{{source.source}}：{{source.count}}条 · 最新发布时间 {{stamp(source.latest_published_at)}} · {{source.age_hours>24?'超过24小时，不能称今日新闻':'24小时内有消息'}}<br><small>最后抓取 {{stamp(source.last_fetched_at)}}（不替代发布时间）</small></p><p v-if="!health.data.value?.sources.length">未保存新闻。管理员需配置数据源/RSS并执行采集，AI不会补造新闻。</p><TaskProgress v-if="jobId" :id="jobId" @finished="q.reload();health.reload()"/></div></section><div class="card"><div class="toolbar"><label>筛选已加载线索<input v-model="filter" placeholder="主题或关键词" aria-label="筛选新闻"></label><label for="news-age-filter">发布时间<select id="news-age-filter" aria-label="发布时间" v-model.number="hours"><option :value="0">全部已加载</option><option :value="24">24小时内</option><option :value="72">3天内</option><option :value="168">7天内</option></select></label><small>已保存记录 · 最多100条；筛选仅限加载范围</small></div><PageState :loading="q.loading.value" :error="q.error.value" :empty="!rows.length" title="暂无匹配的新闻记录" description="在设置中更新数据，或清除筛选。没有抓到的数据不会由 AI 补造。" @retry="q.reload"><article v-for="item in rows" :key="String(item.id)" class="news-card"><div class="actions"><Newspaper :size="15"/><small>{{ item.source }} · {{ stamp(String(item.published_at ?? '')) }}</small><Badge :value="String(record(item.analysis).status ?? 'unknown')" :label="String(record(item.analysis).source ?? '规则分类 / 未标注模型')"/></div><span v-if="ageHours(item.published_at)>24" class="badge">历史消息 · {{Math.floor(ageHours(item.published_at)/24)}}天前</span><h3>{{ item.title }}</h3><p>{{ item.summary }}</p><p v-if="Array.isArray(item.risk_flags)">{{ item.risk_flags.join('；') }}</p><a v-if="safeUrl(item.url)" :href="safeUrl(item.url)" target="_blank" rel="noopener noreferrer">查看原始来源 <ExternalLink :size="11"/></a></article></PageState></div></template>
