<script setup lang="ts">
import { computed, onBeforeUnmount, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import { Settings, UserRound, Database, Monitor, RefreshCw, Link2, ShieldCheck } from 'lucide-vue-next'
import { api, errorText } from '../lib/api'
import { useQuery } from '../lib/query'
import { useSession } from '../stores/session'
import { stamp, olderThan, statusName } from '../lib/format'
import type { Device, Status, DataJob } from '../lib/types'
import Badge from '../components/Badge.vue'
import PageState from '../components/PageState.vue'
interface Preferences { daily_review: boolean; sidebar: 'expanded'|'compact'|'hidden'; reduce_motion: boolean }
const route = useRoute(), session = useSession(), profile = computed(() => route.path === '/profile')
const q = useQuery<Status>('/api/workspace/status'), pref = useQuery<Preferences>('/api/workspace/preferences'), devices = useQuery<{ items: Device[] }>('/api/workspace/devices'), jobs = useQuery<{ items: DataJob[] }>('/api/workspace/data-jobs')
const form = ref<Preferences>({ daily_review: false, sidebar: 'expanded', reduce_motion: false }), busy = ref(false), message = ref(''), error = ref(''), deviceLabel = ref('个人研究设备'), pairing = ref<{ pairing_code: string; expires_at: string } | null>(null), codes = ref(''), lookback = ref(420)
const admin = computed(() => session.role === 'admin' || !session.identifier)
watch(pref.data, value => { if (value) form.value = { ...value } })
async function act(fn: () => Promise<void>) { if (busy.value) return; busy.value = true; error.value = ''; message.value = ''; try { await fn() } catch (e) { error.value = errorText(e) } finally { busy.value = false } }
async function save() { await act(async () => { form.value = await api<Preferences>('/api/workspace/preferences', { method: 'PUT', body: form.value }); window.dispatchEvent(new CustomEvent('workspace-preferences', { detail: form.value })); message.value = '偏好已保存。盘后自动任务还需服务端开关、工作器和真实数据就绪。' }) }
async function pair() { await act(async () => { pairing.value = await api('/api/workspace/devices/pairing', { method: 'POST', body: { label: deviceLabel.value } }); await devices.reload() }) }
async function revoke(id: string) { if (!window.confirm('撤销此设备？未完成的租约将失效，设备不能继续上传结果。')) return; await act(async () => { await api(`/api/workspace/devices/${id}`, { method: 'DELETE' }); pairing.value = null; await devices.reload() }) }
async function queue(task: string) { await act(async () => { const selected = codes.value.split(/[\s,，]+/).map(s => s.trim().toUpperCase()).filter(Boolean); await api(task === 'onboard' ? '/api/workspace/onboard' : '/api/workspace/data-jobs', { method: 'POST', body: { task, codes: selected, lookback_days: lookback.value, request_key: crypto.randomUUID() } }); message.value = '后台任务已排队，页面无需等待数据源。请在下方查看步骤和结果。'; await jobs.reload() }) }
onBeforeUnmount(() => { pairing.value = null })
</script>
<template><div class="page-heading"><div><span class="eyebrow">{{ profile ? 'YOUR PRIVATE SPACE' : 'CONNECTIONS & OPERATIONS' }}</span><h1>{{ profile ? '个人中心' : '设置与连接' }}</h1><p>账户、数据源与研究设备各自独立；不要向页面、日志或代码仓库粘贴登录凭据。</p></div><button class="button" @click="q.reload();devices.reload();jobs.reload()"><RefreshCw :size="14"/>刷新状态</button></div><div v-if="error" class="form-error" role="alert">{{ error }}</div><div v-if="message" class="notice" role="status">{{ message }}</div>
<div class="two-columns section"><div class="card"><div class="card-header"><h2><UserRound :size="16"/>账户与偏好</h2></div><div class="card-body"><dl class="details-list"><dt>当前用户</dt><dd>{{ session.identifier ?? '本地无认证模式（不得公网开放）' }}</dd><dt>角色</dt><dd>{{ session.role ?? '离线单用户' }}</dd><dt>安全会话</dt><dd>HttpOnly Cookie + CSRF · 退出即清理私有页面状态</dd></dl><PageState :loading="pref.loading.value" :error="pref.error.value" @retry="pref.reload"><form @submit.prevent="save"><label class="field">侧栏形态<select v-model="form.sidebar"><option value="expanded">展开</option><option value="compact">窄栏</option><option value="hidden">隐藏</option></select></label><label class="checkbox-label"><input v-model="form.reduce_motion" type="checkbox">减少动效</label><label class="checkbox-label"><input v-model="form.daily_review" type="checkbox">允许在每日盘后条件满足时，为当前账户创建一次复盘任务（默认关闭）</label><p class="small-note">只是任务授权，不是自动发布或下单。真实模型执行另受设备状态与预算限制。</p><button class="button primary" :disabled="busy">保存偏好</button></form></PageState></div></div><div class="card"><div class="card-header"><h2><Database :size="16"/>数据与服务状态</h2></div><div class="card-body"><PageState :loading="q.loading.value" :error="q.error.value" @retry="q.reload"><dl v-if="q.data.value" class="details-list"><dt>应用 / 工作站</dt><dd>{{ q.data.value.app_version }} / {{ q.data.value.workspace_version }}</dd><dt>数据模式</dt><dd><Badge :value="q.data.value.market_provider"/></dd><dt>证券目录 / 跟踪池</dt><dd>{{ q.data.value.catalog_count }} / {{ q.data.value.tracked_count }}</dd><dt>后台工作器</dt><dd><Badge :value="olderThan(q.data.value.worker?.last_seen_at,90) ? 'stale' : 'active'" :label="olderThan(q.data.value.worker?.last_seen_at,90) ? '离线 / 未连接' : '心跳正常'"/><small>{{ stamp(q.data.value.worker?.last_seen_at) }}</small></dd><dt>指标版本</dt><dd>{{ q.data.value.indicator_version }}</dd><dt>策略版本</dt><dd>{{ q.data.value.strategy_version }}</dd><dt>14:30 资格</dt><dd>尚未取得历史回测资格</dd></dl></PageState><p class="small-note">数据密钥通过服务端安全配置管理。此版本不提供明文数据库 API Key 输入框。</p></div></div></div>
<div class="card section"><div class="card-header"><h2><Monitor :size="16"/>隔离研究设备</h2><Badge :value="q.data.value?.bridge_enabled ? 'active' : 'unknown'" :label="q.data.value?.bridge_enabled ? '桥接已开放' : '桥接默认关闭'"/></div><div class="card-body"><div class="notice"><ShieldCheck :size="16"/><span>网站不读取本机 Codex 登录文件。独立 CODEX_HOME 的官方登录只在设备完成；设备只能领取任务和上传候选，不能发布或改持仓。</span></div><form class="actions" @submit.prevent="pair"><input v-model="deviceLabel" aria-label="设备名称" maxlength="64" required><button class="button" :disabled="busy || !q.data.value?.bridge_enabled"><Link2 :size="15"/>生成一次性配对码</button></form><div v-if="pairing" class="section"><p class="small-note">在自己的 Bridge 终端交互输入此码，不提交到 Git，不作为模型 Token。到期 {{ stamp(pairing.expires_at) }}。</p><div class="device-code">{{ pairing.pairing_code }}</div><button class="text-button" @click="pairing = null">隐藏配对码</button></div><PageState :loading="devices.loading.value" :error="devices.error.value" :empty="!devices.data.value?.items.length" title="尚无已配对设备" description="未连接 AI 不影响行情、图表、自选和持仓。" @retry="devices.reload"><ul class="job-list"><li v-for="device in devices.data.value?.items" :key="device.device_id"><div><strong>{{ device.label }}</strong><p><Badge :value="device.status"/> · 最后上报 {{ stamp(device.last_seen_at) }}</p><small>设备自报登录状态：{{ device.heartbeat?.login_state ?? '未知' }} · {{ device.heartbeat?.mode ?? '未运行' }}</small></div><button class="button small" :disabled="busy || device.status === 'revoked'" @click="revoke(device.device_id)">撤销</button></li></ul></PageState></div></div>
<div class="card section"><div class="card-header"><h2><Settings :size="16"/>确定性数据任务</h2><small>页面只排队；Provider 采集与计算在工作器中执行</small></div><div class="card-body"><div class="form-grid"><label class="field">显式 ETF / LOF 代码（逗号分隔）<input v-model="codes" aria-label="同步基金代码" placeholder="512480.SH,510300.SH"></label><label class="field">历史回溯天数<input v-model.number="lookback" type="number" min="30" max="1800"></label><div class="field"><span>运行限制</span><small>单工作器、有界队列；不存在的基金或不可用的数据源会明确失败。</small></div></div><div class="actions"><button class="button primary" :disabled="busy || !codes.trim()" @click="queue('onboard')">初始化选中基金（最多 3 只）</button><button v-if="admin" class="button" :disabled="busy" @click="queue('refresh')">更新目录与跟踪池数据</button><button v-if="admin" class="button" :disabled="busy" @click="queue('factors')">因子诊断</button><button v-if="admin" class="button" :disabled="busy" @click="queue('shadow_audit')">影子运行审计</button></div><p class="small-note">不会自动调用模型，也不会把验证结果自动提升为合格。大规模 OOS 验证应在独立预算下执行。</p></div><PageState :loading="jobs.loading.value" :error="jobs.error.value" :empty="!jobs.data.value?.items.length" title="暂无数据任务" description="先提交一次初始化或刷新；真实数据源需要在部署环境中配置。" @retry="jobs.reload"><ul class="job-list"><li v-for="job in jobs.data.value?.items" :key="job.job_id"><div><strong>{{ job.task }} · {{ job.codes?.join(', ') || '目录 / 跟踪池' }}</strong><p><Badge :value="job.status"/> · {{ stamp(job.created_at) }}</p><small v-if="job.failure_reason">失败原因：{{ job.failure_reason }}</small><details v-if="job.result" class="details-block"><summary>查看步骤与诊断</summary><pre class="report-text">{{ JSON.stringify(job.result, null, 2) }}</pre></details></div></li></ul></PageState></div></template>
