export type Json = string | number | boolean | null | Json[] | { [key: string]: Json }
export interface Metric { label?: string; kind?: string; status?: string; value?: number | null; j?: number | null; [key: string]: unknown }
export interface Quote { price: number | null; change_ratio?: number | null; status: string; source_time?: string | null; fetched_at?: string | null; source?: string | null; is_mock?: boolean }
export interface ModuleAvailability { status: string; reason_code: string | null; by_horizon?: Record<string, { status: string; reason_code: string | null }> }
export interface DetailAvailability { instrument: ModuleAvailability; price: ModuleAvailability; history: ModuleAvailability; price_basis: ModuleAvailability; indicators: ModuleAvailability; volume: ModuleAvailability; forecasts: ModuleAvailability; decision: ModuleAvailability; support_resistance?: ModuleAvailability }
export interface DecisionExplanation { conclusion: string | null; primary_basis: string | null; comparison: Record<string, unknown>; evidence_caveats: string[]; computed_at: string | null; actionable: false }
export interface Forecast { p_up?: number | null; expected_return?: number | null; q10?: number | null; q50?: number | null; q90?: number | null; sample_count?: number; confidence?: number | string | null; calibration_status?: string; probability_label?: string; model_version?: string; as_of_date?: string; terminal_price_q10?: number | null; terminal_price_q50?: number | null; terminal_price_q90?: number | null; [key: string]: unknown }
export interface BoardRow { ts_code: string; name: string; theme_l1?: string; theme_l2?: string; grade: string; grade_reason?: string; freshness?: string; data_status?: string; price?: number | null; return_1d?: number | null; return_5d?: number | null; volume?: Metric; ma?: Metric; macd?: Metric; kdj?: Metric; rsi?: Metric; td?: Metric; sector?: Metric; forecasts?: Record<string, Forecast>; indicator?: Record<string, unknown>; entry_exit_ref?: Record<string, unknown>; theme_relative_strength?: Record<string, unknown>; support_resistance?: SupportResistance | null }
export interface Overview { snapshot_id: string | number | null; generated_at: string | null; freshness_at_capture: string; rows: BoardRow[]; total: number; offset: number; limit: number; themes: string[]; contains_mock: boolean; counts: Record<string, number>; scope: string }
export interface SearchItem { match_reason?:string; market_cap_cny?:number|null; turnover_cny?:number|null; metadata_as_of?:string; ts_code: string; name: string; kind: string; theme?: string; enabled: boolean; watched: boolean; held: boolean; quote: Quote }
export interface Holding { ts_code: string; name: string; kind: string; theme: string; shares: number; cost_price: number; quote: Quote; market_value: number | null; pnl: number | null; pnl_ratio: number | null; weight: number | null; grade: string; forecasts: Record<string, Forecast>; support_resistance?: SupportResistance | null; target_weight?: number | null; notes?: string | null; updated_at?: string }
export interface Holdings { items: Holding[]; priced_subtotal: number; total_market_value: number | null; pricing_complete: boolean; unpriced_count: number; weight_basis: string; data_warning: string }
export interface SupportLevel { price?: number; level?: number; zone_low?: number; zone_high?: number; kind?: string; type?: string; label?: string; strength?: number; [key: string]: unknown }
export interface SupportResistance { levels?: SupportLevel[]; nearest_support?: SupportLevel | number | null; nearest_resistance?: SupportLevel | number | null; source_as_of_date?: string; snapshot_as_of_date?: string; qualified?: boolean; reason?: string; [key: string]: unknown }
export interface PriceBox { kind: 'daily_box'; structure_id: string; lower: number; upper: number; mid: number; origin_at: string; confirmed_at: string | null; valid_from?: string | null; valid_until?: string | null; state: string; upper_touch_count: number; lower_touch_count: number; touch_count: number; source_ids: string[]; inside_ratio?: number; width_atr?: number; volume_confirmation_available: boolean; intraday_state?: { state: 'breakout_attempt'; side: 'upper' | 'lower' | 'both'; observed_at?: string | null; source_id?: string } | null }
export interface LivePriorRange { kind: 'prior_high_low'; qualified: false; actionable: false; persisted: false; window: number; origin_at: string; valid_until: string; upper: number; lower: number; upper_date?: string; lower_date?: string; label?: string; disclaimer?: string }
export interface PriceStructures { qualified: boolean; reason?: string | null; interval: string; source_as_of_date?: string | null; read_as_of?: string | null; price_basis_id?: string | null; input_hash?: string | null; actionable: false; boxes: PriceBox[]; candidate?: Record<string, unknown> | null; live_prior_range?: LivePriorRange | null }
export interface ChanTransition { structure_key?: string | null; status?: string | null; revision_id?: string | null; prior_revision_id?: string | null; reappearance?: boolean | null }
export interface ChanRevisionEvidence { sequence_number?: number | null; cutoff_at?: string | null; input_revision_id?: string | null; input_hash?: string | null; transitions?: ChanTransition[] | null }
export interface ChanFractal { date: string; price: number; mark: 'top' | 'bottom'; source: 'persisted' }
export interface ChanObservation { fx?: ChanFractal[]; undrawable_fx?: number; revision_evidence?: ChanRevisionEvidence | null; observation_id?: string | null; engine_id?: string | null; engine_version?: string | null; dialect_id?: string | null; price_basis_id?: string | null; view_semantics?: string | null; settlement_status?: 'settled' | 'temporary' | 'unknown' | null; available?: boolean; drawable?: boolean; fallback_allowed?: boolean; qualified?: false; actionable?: false; source?: string | null; reason_code?: string | null; disclaimer?: string; counts?: { fx?: number; bi?: number; zs?: number }; bi?: Array<Record<string, unknown>>; segments?: Array<Record<string, unknown>>; zhongshu?: Array<Record<string, unknown>>; undrawable_bi?: number }
export interface Detail { instrument: { ts_code: string; name: string; kind: string; theme_l1: string; theme_l2: string; enabled?: boolean }; decision: BoardRow | null; decision_explanation?: DecisionExplanation; availability?: DetailAvailability; availability_contract_version?: "detail-availability-v1"; snapshot_id: string | number | null; decision_time: string | null; read_as_of?: string | null; indicator_input_hash?: string | null; chart_series_id?: string | null; indicator_basis?: string; quote: Quote; indicator_values: Record<string, number | string | null>; indicator_version: string | null; indicator_as_of: string | null; forecasts: Record<string, Forecast>; support_resistance: SupportResistance | null; holding: Holding | null; forecast_scenario: unknown; history_issue?: string | null }
export interface ChartBar { date: string; open: number; high: number; low: number; close: number; volume: number | null; amount: number | null; is_partial?: boolean; source?: string; indicators: Record<string, number | null> }
export interface Reading { key:string; label:string; value:number|null; previous:number|null; change:number|null; change_ratio:number|null; explanation:string }
export interface ChartData { studies?: SupportResistance & {readings?:Reading[]; chan_structure?: unknown}; chan_observation?: ChanObservation | null; ts_code: string; interval: string; available: boolean; bars: ChartBar[]; research_bars?: ChartBar[]; reason?: string | null; adjust?: string; display_price_basis?: string; research_price_basis?: string; research_price_basis_id?: string; research_basis_evidence_ids?: string[]; indicator_basis?: string; input_hash?: string; series_id?: string; chart_contract_version?: string; basis_transition?: boolean; raw_overlay_allowed?: boolean; raw_overlay_reason?: string | null; research_cost_overlay_allowed?: boolean; research_sr_overlay_allowed?: boolean; research_support_resistance?: SupportResistance | null; price_structures?: PriceStructures; research_price_structures?: PriceStructures; qualification?: string; indicator_note?: string; indicator_version?: string; core_snapshot_match?: boolean | null; history_truncated?: boolean; history_issue?: string | null; source_as_of?: string; as_of?: string | null; computed_at?: string | null; cost_overlay_allowed?: boolean; sr_overlay_allowed?: boolean; support_resistance?: SupportResistance | null }
export interface Claim { text: string; evidence_ids: string[] }
export interface ResearchResult { schema_version: string; job_id: string; input_hash: string; producer: string; producer_version: string; model: string; summary: string; facts: Claim[]; inferences: Claim[]; risks: string[]; conflicts: string[]; limitations: string[]; evidence_ids: string[]; report_markdown: string }
export interface ResearchJob { origin?: string; upstream_status?: string; job_id: string; kind: string; ts_code?: string | null; status: string; quality: string; review_status: string; input_hash: string; result_hash?: string | null; source_as_of?: string | null; created_at: string; expires_at: string; expired: boolean; attempts: number; summary?: string | null; failure_reason?: string | null; result?: ResearchResult | null; evidence?: Record<string, unknown>[] }
export interface ImportCandidate { row_index: number; ts_code: string; name?: string | null; shares: string; cost_price: string; selected: boolean; errors: string[] }
export interface ImportBatch { batch_id: string; status: string; source_kind: string; expires_at: string; candidates: ImportCandidate[]; candidate_hash: string; note: string }
export interface Device { device_id: string; label: string; status: string; last_seen_at: string | null; heartbeat?: { bridge_version: string; login_state: string; mode: string } | null }
export interface Status { app_version: string; workspace_version: string; strategy_version: string; indicator_version: string; forecast_version: string; market_provider: string; bridge_enabled: boolean; daily_review_enabled: boolean; catalog_count: number; tracked_count: number; worker?: { last_seen_at: string } | null; historical_1430_backtest: string }
export interface DataJob { job_id: string; task: string; status: string; created_at: string; finished_at?: string; codes: string[]; failure_reason?: string; result?: { current_step?: string; steps?: { task: string; status: string; reason?: string }[] } | null }