export type Json = string | number | boolean | null | Json[] | { [key: string]: Json }
export interface Metric { label?: string; kind?: string; status?: string; value?: number | null; j?: number | null; [key: string]: unknown }
export interface Quote { price: number | null; change_ratio?: number | null; status: string; source_time?: string | null; source?: string | null; is_mock?: boolean }
export interface Forecast { p_up?: number | null; expected_return?: number | null; q10?: number | null; q50?: number | null; q90?: number | null; sample_count?: number; confidence?: number | string | null; calibration_status?: string; probability_label?: string; model_version?: string; as_of_date?: string; terminal_price_q10?: number | null; terminal_price_q50?: number | null; terminal_price_q90?: number | null; [key: string]: unknown }
export interface BoardRow { ts_code: string; name: string; theme_l1?: string; theme_l2?: string; grade: string; grade_reason?: string; freshness?: string; data_status?: string; price?: number | null; return_1d?: number | null; return_5d?: number | null; volume?: Metric; ma?: Metric; macd?: Metric; kdj?: Metric; rsi?: Metric; td?: Metric; forecasts?: Record<string, Forecast>; indicator?: Record<string, unknown> }
export interface Overview { snapshot_id: string | number | null; generated_at: string | null; freshness_at_capture: string; rows: BoardRow[]; total: number; offset: number; limit: number; themes: string[]; contains_mock: boolean; counts: Record<string, number>; scope: string }
export interface SearchItem { ts_code: string; name: string; kind: string; theme?: string; enabled: boolean; watched: boolean; held: boolean; quote: Quote }
export interface Holding { ts_code: string; name: string; kind: string; theme: string; shares: number; cost_price: number; quote: Quote; market_value: number | null; pnl: number | null; pnl_ratio: number | null; weight: number | null; grade: string; forecasts: Record<string, Forecast>; support_resistance?: SupportResistance | null; target_weight?: number | null; notes?: string | null; updated_at?: string }
export interface Holdings { items: Holding[]; priced_subtotal: number; total_market_value: number | null; pricing_complete: boolean; unpriced_count: number; weight_basis: string; data_warning: string }
export interface SupportLevel { price?: number; level?: number; zone_low?: number; zone_high?: number; kind?: string; type?: string; label?: string; strength?: number; [key: string]: unknown }
export interface SupportResistance { levels?: SupportLevel[]; nearest_support?: SupportLevel | number | null; nearest_resistance?: SupportLevel | number | null; source_as_of_date?: string; snapshot_as_of_date?: string; qualified?: boolean; reason?: string; [key: string]: unknown }
export interface Detail { instrument: { ts_code: string; name: string; kind: string; theme_l1: string; theme_l2: string }; decision: BoardRow | null; snapshot_id: string | number | null; decision_time: string | null; quote: Quote; indicator_values: Record<string, number | string | null>; indicator_version: string | null; indicator_as_of: string | null; forecasts: Record<string, Forecast>; support_resistance: SupportResistance | null; holding: Holding | null; forecast_scenario: unknown }
export interface ChartBar { date: string; open: number; high: number; low: number; close: number; volume: number | null; amount: number | null; is_partial?: boolean; source?: string; indicators: Record<string, number | null> }
export interface ChartData { ts_code: string; interval: string; available: boolean; bars: ChartBar[]; reason?: string | null; adjust?: string; qualification?: string; indicator_note?: string; indicator_version?: string; core_snapshot_match?: boolean | null; history_truncated?: boolean; source_as_of?: string; cost_overlay_allowed?: boolean; sr_overlay_allowed?: boolean; support_resistance?: SupportResistance | null }
export interface Claim { text: string; evidence_ids: string[] }
export interface ResearchResult { schema_version: string; job_id: string; input_hash: string; producer: string; producer_version: string; model: string; summary: string; facts: Claim[]; inferences: Claim[]; risks: string[]; conflicts: string[]; limitations: string[]; evidence_ids: string[]; report_markdown: string }
export interface ResearchJob { job_id: string; kind: string; ts_code?: string | null; status: string; quality: string; review_status: string; input_hash: string; result_hash?: string | null; source_as_of?: string | null; created_at: string; expires_at: string; expired: boolean; attempts: number; summary?: string | null; failure_reason?: string | null; result?: ResearchResult | null; evidence?: Record<string, unknown>[] }
export interface ImportCandidate { row_index: number; ts_code: string; name?: string | null; shares: string; cost_price: string; selected: boolean; errors: string[] }
export interface ImportBatch { batch_id: string; status: string; source_kind: string; expires_at: string; candidates: ImportCandidate[]; candidate_hash: string; note: string }
export interface Device { device_id: string; label: string; status: string; last_seen_at: string | null; heartbeat?: { bridge_version: string; login_state: string; mode: string } | null }
export interface Status { app_version: string; workspace_version: string; strategy_version: string; indicator_version: string; forecast_version: string; market_provider: string; bridge_enabled: boolean; daily_review_enabled: boolean; catalog_count: number; tracked_count: number; worker?: { last_seen_at: string } | null; historical_1430_backtest: string }
export interface DataJob { job_id: string; task: string; status: string; created_at: string; finished_at?: string; codes: string[]; failure_reason?: string; result?: { current_step?: string; steps?: { task: string; status: string; reason?: string }[] } | null }
